{*
8/4/2009 1:09:37 PM Andy
- add selling price change function
- add reset function

2/8/2010 4:52:59 PM Andy
- Add new consignment type: consignment over invoice

7/13/2010 5:44:32 PM Andy
- Remove open info in consignment invoice.
- Add settings for consignment invoice.
- Able to control whether use item discount or not.
- Able to control whether split invoice by price type or not when confirm.

10/12/2010 5:48:26 PM Andy
- Add new setting: Auto bring item discount to sheet discount when confirm. (Only if there is no split and all items have same discount percent). (can control by config to turn it default on)
- Fix Use item branch trade discount bugs, if user tick and untick too fast, it maybe display wrong data.

3/30/2011 1:37:17 PM Justin
- Fixed the rounding problem while calculating discount amount and total amount after discounted.
- Added a new feature to return user 100% maximum discount only if user tried to key in discount more than 100%.

5/9/2011 3:48:00 PM Andy
- Fix a bugs cause wrong calculation, due to after javascript round2 it become string.

6/22/2011 10:58:23 AM Andy
- Make SKU autocomplete default select artno as search type when consignment mode.

7/5/2011 4:17:33 PM Justin
- Added the missing checking of foreign fields.
- Added to pass currency code parameter while adding new item.

7/6/2011 10:17:33 AM Justin
- Fixed the discount for foreign amount field did not hide/show while using currency rate.

7/6/2011 9:59:20 AM Andy
- Fix default branch_id blank problem.

11/9/2011 4:56:43 PM Justin
- Fixed bug of price type does not renew when branch of Invoice To has been changed.

11/9/2011 5:17:43 PM Justin
- Added to replace cost price with selling price when found config cm_use_deliver_branch_sp.

12/15/2011 2:05:43 PM Justin
- Added to re-calculate selling price when uom changed.
- Modified to update selling price currency code whenever found deliver branch is oversea.

3/26/2012 3:36:32 PM Justin
- Modified to detect price_type instead of price_type_id.

9/14/2012 4:39 PM Drkoay
- Added Discount Selling Price (%)
- Added Discount Item Row(%)
- rewrite function recal_total()
- rewrite function calc_all_items()
- rewrite function recal_total()
- comment function select_type() (not using)
- comment function foreign_variable_recalc() (not using)
- update function uom_change (comment calling function foreign_variable_recalc)
- update function foreign_variable_handler (comment calling function foreign_variable_recalc)

9/26/2012 PM Drkoay
- change Discount Item Row to Bearing Percent

11/23/2012 2:17:00 PM Fithri
- after monthly report has been printed, user cannot do further edit (reject, approval or submit) on that month - for consignment only

1/25/2013 4:46 PM Justin
- Enhanced to disable Deliver To dropdown list when found it is generated by Monthly Report.

8/1/2013 2:37 PM Fithri
- bugfix : add checking for items in temp table before save/confirm in case the document is open in more than one tab/window

12/23/2013 10:23 AM Fithri
- new module 'Stucked Documents Approval'

12/24/2013 3:49 PM Andy
- Fix row number does not appear after new item was added.

3/24/2014 5:27 PM Justin
- Modified the wording from "Finalize" to "Finalise".

1/17/2015 11:23 AM Justin
- Enhanced to have GST calculation.

3/26/2015 3:18 PM Justin
- Enhanced to have new feature that calculate from GST price into net price.

3/31/2015 5:46 PM Andy
- Fix when change "To branch" will load the wrong selling price.
- Temporary remove the feature is_export checkbox.

5/8/2015 11:17 AM Andy
- Fix the invoice calculation.

5/13/2015 5:48 PM Andy
- Change the ajax add item to use json instead of xml.
- Enhanced to have display cost price feature.

5/18/2015 2:11 PM Andy
- Fix gst rounding calculation.

5/19/2015 9:56 AM Andy
- Fix js error when not under gst.
- Fix Bearing percent din't calculate.
- Fix cost price din't recalculate when foreign cost price is change, for non-gst invoice.
- Fix ctn pcs open/hide error.

6/4/2015 10:43 AM Andy
- Fix foreign discount calculation.

6/9/2015 5:22 PM Andy
- Fix js error if no foreign.

6/10/2015 5:13 PM Andy
- Fix multiple add layout.

6/19/2015 3:41 PM Andy
- Fix cost price rounding issue when no GST.

8/27/2015 4:04 PM Andy
- Fix change branch reload foreign price bugs.

9/3/2015 11:24 AM Andy
- Change the cost price label to 4 decimal when change display cost price.

12/4/2015 9:21AM DingRen
- add check login for form submit and ajax call
*}



<script type="text/javascript">
{if $form.type}
	{assign var=page_type value=$form.type}
{else}
    {assign var=page_type value=$smarty.request.type|default:'sales'}
{/if}

{*
{if $page_type eq 'over' or $page_type eq 'lost'}
  {assign var=show_per value=1}
{/if}
*}
var page_type = '{$page_type}'
var create_type="{$form.create_type}";
var php_self = '{$smarty.server.PHP_SELF}';
var cm_use_deliver_branch_sp = '{$config.cm_use_deliver_branch_sp}';
//var show_per = '{$form.show_per}';

</script>

{assign var=time_value value=1000000000}

{if !$form.approval_screen}
	{include file=header.tpl}
{else}
	<hr noshade size=2>
{/if}



{literal}
<link rel="stylesheet" type="text/css" media="all" href="js/jscalendar/calendar-blue.css" title="calendar-blue" />
<script type="text/javascript" src="js/jscalendar/calendar.js"></script>
<script type="text/javascript" src="js/jscalendar/lang/calendar-en.js"></script>
<script type="text/javascript" src="js/jscalendar/calendar-setup.js"></script>

<style>
.sh{
    background-color:#ff9;
}

.stdframe.active{
 	background-color:#fea;
	border: 1px solid #f93;
}

td.xc{
	border-bottom: 1px dashed #aaa;
}

.input_no_border input, .input_no_border select{
	border:1px solid #999;
	background: #fff;
	font-size: 10px;
	padding:2px;
}
input[disabled],input[readonly],select[disabled], textarea[disabled]{
  color:black;
  background: #ddd;
}
</style>
{/literal}
<script type="text/javascript">
var approval_screen = '{$form.approval_screen}';
var consignment_modules = '{$config.consignment_modules}';
var masterfile_branch_region = '{$config.masterfile_branch_region}';
var consignment_multiple_currency = '{$config.consignment_multiple_currency}';
var phpself = '{$smarty.server.PHP_SELF}';

// gst
var enable_gst = int('{$config.enable_gst}');
var global_gst_start_date = '{$config.global_gst_start_date}';
var is_under_gst = int('{$form.is_under_gst}');
var branch_gst_register_no = '{$sessioninfo.gst_register_no}';
var branch_gst_start_date = '{$sessioninfo.gst_start_date}';
var gst_is_active = int('{$sessioninfo.gst_is_active}');
var skip_gst_validate = int('{$sessioninfo.skip_gst_validate}');
var gst_export = '{$gst_export_settings.id}';

var branch_currency_code = [];
var branch_exchange_rate = [];
{if $config.consignment_modules && $config.masterfile_branch_region && $config.consignment_multiple_currency}
	{foreach from=$branches item=b}
		{if $form.ci_branch_id eq $b.id}
			{assign var=exchange_rate value=$form.exchange_rate}
		{else}
			{assign var=exchange_rate value=$b.exchange_rate}
		{/if}
		branch_currency_code['{$b.id}'] = "{$b.currency_code|escape:javascript}";
		branch_exchange_rate['{$b.id}'] = "{$exchange_rate|escape:javascript}";
	{/foreach}
{/if}

{literal}
var active_search_box = 'ajax_autocomplete';
function ci_save(){
	document.f_a.a.value='save';
	document.f_a.target = "";
	if(check_a() && chk_open_info()){
		
		center_div('wait_popup');
		curtain(true,'curtain2');
		Element.show('wait_popup');
		
		ajax_request('consignment_invoice.php',{
			method: 'post',
			parameters: Form.serialize(document.f_a)+'&a=check_tmp_item_exists',
			onComplete: function(e){
				if (e.responseText.trim() == 'OK') {
					document.f_a.submit();	
					return;
				}
				else {
					Element.hide('wait_popup');
					curtain(false,'curtain2');
					alert(e.responseText.trim());
					return;
				}
			}
		});
	} 
}

function ci_confirm(){
	if(check_a() && chk_open_info()){
		if (confirm('Finalise CI and submit for approval?')){
		
			center_div('wait_popup');
			curtain(true,'curtain2');
			Element.show('wait_popup');
		
			ajax_request('consignment_invoice.php',{
				method: 'post',
				parameters: Form.serialize(document.f_a)+'&a=check_tmp_item_exists',
				onComplete: function(e){
					if (e.responseText.trim() == 'OK') {
						document.f_a.a.value = "confirm";
						document.f_a.target = "";
						document.f_a.submit();
						return;
					}
					else {
						Element.hide('wait_popup');
						curtain(false,'curtain2');
						alert(e.responseText.trim());
						return;
					}
				}
			});
		}	
	}
}

function check_a(){
	if (empty(document.f_a.ci_date, "You must enter CI Date")){
	    return false;
	}
	return true;
}

function ajax_add(parms)
{
	if(masterfile_branch_region && consignment_multiple_currency) parms += "&currency_code="+branch_currency_code[document.f_a['ci_branch_id'].value];

	ajax_request("consignment_invoice.php",{
		method:'post',
		parameters: parms,
		evalScripts: true,
		onFailure: function(m) {
			alert(m.responseText);
		},
		onSuccess: function (m) {
            //var tb = $('ci_items');
			
			// insert the html at the div bottom
				var str = m.responseText.trim();
				var ret = {};
			    var err_msg = '';

			    try{
	                ret = JSON.parse(str); // try decode json object
	                if(ret['ok'] && ret['html']){ // success
	                    new Insertion.Bottom('ci_items', ret['html']);
					}else{  // save failed
						if(ret['failed_reason'])	err_msg = ret['failed_reason'];
						else    err_msg = str;
					}
				}catch(ex){ // failed to decode json, it is plain text response
					err_msg = str;
				}

			    // prompt the error
			    if(err_msg)	alert(err_msg);
				
            /*var lbody;
			var xml = m.responseXML;
			
			if (!xml) { alert(m.responseText); return; }
			var records = xml.getElementsByTagName("record");
	        // Get the text from an XML tag.
			$A(records).each(
			    function(r,idx){
				    var rowitem = tb.insertRow(-1);
				    rowitem.id = "titem"+xml_getData(r, "id").strip();
				    rowitem.innerHTML = xml_getData(r,'rowdata');
				    //row_recalc(xml_getData(r, "id").strip());
				    row_recalc(rowitem);
			});*/
			reset_row();
		},
	});
}

function add_grn_barcode_item(value)
{
	value = trim(value);
	if (value=='')
	{
		$('grn_barcode').select();
		$('grn_barcode').focus();
		return;
	}
	$('grn_barcode').value='';
	ajax_add(Form.serialize(document.f_a)+'&a=ajax_add_grn_barcode_item&grn_barcode='+value);
	active_search_box = 'grn_barocde';
}

function add_item(){
	if (int(document.f_a.sku_item_id.value)==0){
	    alert('No item selected');
	    return false;
	}
	ajax_add(Form.serialize(document.f_a)+'&a=ajax_add_item&type='+page_type);
	active_search_box = 'ajax_autocomplete';
}
	
function ci_cancel(){
    if (check_login()) {
        if (confirm('Cancel this CI?')){
            document.f_a.a.value='cancel';
            document.f_a.target = "";
            document.f_a.submit();
        }
    }
}

function ci_delete(){
    if (check_login()) {
        document.f_a.reason.value = '';
        var p = prompt('Enter reason to Delete :');
        if (p.trim()=='' || p==null) return;
        document.f_a.reason.value = p;
        if (confirm('Delete this CI?')){
            document.f_a.a.value = "delete";
            document.f_a.submit();
        }
    }
}


function uom_change(value,id){
	var a = value.split(",");
	old_cost=float($('cost_price_'+id).value)/float($('uom_fraction'+id).value);
	new_cost=old_cost*float(a[1]);
	$('cost_price_'+id).value=round(new_cost,3);
	var old_selling = float($('selling_price_'+id).value)/float($('uom_fraction'+id).value);
	var new_selling = old_selling*float(a[1]);
	$('selling_price_'+id).value=round(new_selling,2);
	
	if(consignment_modules && consignment_multiple_currency){
		var old_foreign_cost=float($('foreign_cost_price_'+id).value)/float($('uom_fraction'+id).value);
		var new_foreign_cost=old_foreign_cost*float(a[1]);
		$('foreign_cost_price_'+id).value=round(new_foreign_cost,3);
	}
	
	//only re-assign when the CI if created from PO.
	if (create_type==3){
		old_po_cost=float($('po_cost_'+id).value)/float($('uom_fraction'+id).value);
		new_po_cost=old_po_cost*float(a[1]);
		$('po_cost_'+id).value=round(new_po_cost,2);	
	}

	$('uom_id'+id).value=a[0];
	$('uom_fraction'+id).value=a[1];
	//document.f_a.elements['uom_id['+id+']'].value = a[0];
	//document.f_a.elements['uom_fraction['+id+']'].value = a[1];
		
	if(($('uom_fraction'+id).value)=='1'){
		var e = $('ci_items').getElementsByClassName('uom');
		for(var i=0;i<e.length;i++)	{
	 		var temp_1 =new RegExp('^qty_ctn'+id);
			if (temp_1.test(e[i].id)) {
				e[i].value='--';
		    	e[i].disabled=true;
			}
		}
	}
	else{		
		var e1 = $('ci_items').getElementsByClassName('uom');
		for(var j=0;j<e1.length;j++){
	 		var temp_2=new RegExp('^qty_ctn'+id);
			if (temp_2.test(e1[j].id)) {
		    	e1[j].disabled=false;
		    	if(e1[j].value=='--'){		    		
		    		e1[j].value='';				
				}
			}
		}
	}
	//if(consignment_modules && consignment_multiple_currency) foreign_variable_recalc();
}

var sku_autocomplete = undefined;
function reset_sku_autocomplete(){
	var param_str = "a=ajax_search_sku&get_last_po=1&type="+getRadioValue(document.f_a.search_type);
	if (sku_autocomplete != undefined){
	    sku_autocomplete.options.defaultParams = param_str;
	}
	else{
		sku_autocomplete = new Ajax.Autocompleter("autocomplete_sku", "autocomplete_sku_choices", "ajax_autocomplete.php", {parameters:param_str, paramName: "value",
		afterUpdateElement: function (obj, li) {
		    s = li.title.split(",");
			document.f_a.sku_item_id.value =s[0];
			document.f_a.sku_item_code.value = s[1];
		}});
	}
	$('autocomplete_sku').focus();
}

function refresh_tables(){
    if (check_login()) {
        document.f_a.a.value = "refresh";
        document.f_a.target = "";
        if(chk_open_info()){
            document.f_a.submit();
        }
    }
}

function chk_open_info(){
	/*if($('delivery_open')!=undefined && $('delivery_open').style.display!='none'){
		if (empty($('oi_name'), "You must enter Company Name")){
		    return false;
		}
		if (empty($('oi_address'), "You must enter Company Address")){
		    return false;
		}
	}*/
	return true;
}


function delete_item(id){
 	if (!confirm('Remove this SKU from CI?')) return;
 	bid = document.f_a.branch_id.value;
	ajax_request("consignment_invoice.php",{
		method:'post',
		parameters: 'a=ajax_delete_item&branch_id='+bid+'&id='+id,
	    evalScripts: true,
		onFailure: function(m) {
			alert(m.responseText);
		},
		onSuccess: function (m) {
            Element.remove('titem'+id);
			calc_all_items();
			reset_row();
    	}
	});
}

function reset_row(){
	var e = $('ci_items').getElementsByClassName('no');
	for(var i=0;i<e.length;i++)	{
 		var temp_1 =new RegExp('^no_');
	 	if (temp_1.test(e[i].id)){
			td_1=(i+1)+'.';
			e[i].innerHTML=td_1;
			e[i].id='no_'+(i+1);
		}
	}

	$(active_search_box).value='';
	$(active_search_box).focus();
}

function init_calendar(){
	Calendar.setup({
		inputField     :    "added1",
		ifFormat       :    "%Y-%m-%d",
		button         :    "t_added1",
		align          :    "Bl",
		singleClick    :    true
	});   
}

var prev_price_indicate;
function refresh_cost(obj)
{
	if (confirm('Change Price Indicate?')){
		new Ajax.Updater('new_sheets', 'consignment_invoice.php', {
			parameters: Form.serialize(document.f_a)+'&a=ajax_refresh_cost',
			evalScripts: true,
			onComplete:  function (m) {
				calc_all_items();
			}
		});
		prev_price_indicate = obj;		
	}
	else{
		prev_price_indicate.checked=true;
	}
}

function change_lost_inv_branch(){
	var bid = $('delivery_branches').value;
	$('span_branch_changed').update(_loading_);
	
	var spans = $('ci_items').getElementsBySelector('span.sku_item_info');
	var sku_item_id_list = [];
	
	// make sku_item_id into array
	for(var i=0; i<spans.length; i++){
        sku_item_id_list.push(spans[i].id.split(',')[1]);
	}
	var form_type = 1;
	/*var form_type = 0;
	var delivery_type = document.f_a['delivery_type'];
	for(var i=0; i<delivery_type.length; i++){

		if(delivery_type[i].checked){
            form_type = delivery_type[i].value;
            break;
		}  
	}
	*/

	if(consignment_modules && masterfile_branch_region && consignment_multiple_currency && document.f_a['ci_branch_id'] != undefined){
		if(document.f_a['ci_branch_id'] != undefined){
			document.f_a.elements['exchange_rate'].value = branch_exchange_rate[document.f_a['ci_branch_id'].value];
		}else{
			document.f_a.elements['exchange_rate'].value = 0;
		}
		if($('new_sheets')!=undefined) foreign_variable_handler(true);
	}

	var show_per = document.f_a['show_per'].checked ? 1 : 0;
	var exchange_rate = 0;
	var hasforeign = check_has_foreign();
	if(hasforeign){
		exchange_rate = document.f_a['exchange_rate'].value;
	}	

	/*new Ajax.Request(php_self,{
		method: 'post',
		parameters: {
			a: 'change_lost_inv_branch',
			branch_id: bid,
			'sku_item_id[]': sku_item_id_list,
			'inv_type': page_type,
			form_type: form_type,
			show_per: show_per,
			'is_under_gst': is_under_gst,
			'exchange_rate': exchange_rate
		},
		onComplete: function(e){
			eval("var json = "+e.responseText);
			
			$('span_branch_changed').update('');

			// update discount percentage if it is lost invoice
            //if(show_per){
            if(json['branch_discount']){
				$('input_discount_percent').value = json['branch_discount'];
	            $('span_branch_discount_per').update(json['branch_discount']);
			}else{
                $('input_discount_percent').value = '';
	            $('span_branch_discount_per').update('');
			}
            //}
            var allow_edit_selling_price = json['allow_edit_selling_price'];
            
            for(var i=0; i<spans.length; i++){
				var sid = spans[i].id.split(',')[1];
				var item_id = spans[i].id.split(',')[2];
				
				// update discount percentage if it is lost invoice
				//if(show_per){
                    if(!json['item_discount'][sid]['value']){
	                    $('row_discount,'+item_id).update('0');
	                    $('input_discount_per,'+item_id).value = '0';
					}else{
	                    $('row_discount,'+item_id).update(json['item_discount'][sid]['value']);
						$('input_discount_per,'+item_id).value = json['item_discount'][sid]['value'];
					}
					
				//}
				$('price_type,'+item_id).value = json['item_discount'][sid]['trade_discount_code'];
				$('trade_discount_code,'+item_id).innerHTML = json['item_discount'][sid]['trade_discount_code'];
				
				if(!json['stock_balance'])  $('stock_balance,'+item_id).value = '';
				else	$('stock_balance,'+item_id).value = json['stock_balance'][sid];
				
				if(!json['selling_price'])  $('selling_price_'+item_id).value = '';
				else{
					if(cm_use_deliver_branch_sp == 1) $('cost_price_'+item_id).value = json['selling_price'][sid];
					$('selling_price_'+item_id).value = json['selling_price'][sid];
				}
				
				if(allow_edit_selling_price)    $('selling_price_'+item_id).readOnly = false;
				else    $('selling_price_'+item_id).readOnly = true;
			}

			if(consignment_modules && masterfile_branch_region && consignment_multiple_currency && document.f_a['ci_branch_id'] != undefined){
				if($('new_sheets')!=undefined) foreign_variable_handler(true);
			}else{
				calc_all_items();
			}
		}
	});*/

	var params = $(document.f_a).serialize()+'&a=change_lost_inv_branch';
	ajax_request(php_self,{
		method: 'post',
		parameters: params,
		onComplete: function(e){
			eval("var json = "+e.responseText);
			
			$('span_branch_changed').update('');

			// update discount percentage if it is lost invoice
            //if(show_per){
            if(json['branch_discount']){
				$('input_discount_percent').value = json['branch_discount'];
	            $('span_branch_discount_per').update(json['branch_discount']);
			}else{
                $('input_discount_percent').value = '';
	            $('span_branch_discount_per').update('');
			}
            //}
            var allow_edit_selling_price = json['allow_edit_selling_price'];
            
            /*for(var i=0; i<spans.length; i++){
				var sid = spans[i].id.split(',')[1];
				var item_id = spans[i].id.split(',')[2];
				
				// update discount percentage if it is lost invoice
				//if(show_per){
                    if(!json['item_discount'][sid]['value']){
	                    $('row_discount,'+item_id).update('0');
	                    $('input_discount_per,'+item_id).value = '0';
					}else{
	                    $('row_discount,'+item_id).update(json['item_discount'][sid]['value']);
						$('input_discount_per,'+item_id).value = json['item_discount'][sid]['value'];
					}
					
				//}
				$('price_type,'+item_id).value = json['item_discount'][sid]['trade_discount_code'];
				$('trade_discount_code,'+item_id).innerHTML = json['item_discount'][sid]['trade_discount_code'];
				
				if(!json['stock_balance'])  $('stock_balance,'+item_id).value = '';
				else	$('stock_balance,'+item_id).value = json['stock_balance'][sid];
				
				if(!json['selling_price'])  $('selling_price_'+item_id).value = '';
				else{
					if(cm_use_deliver_branch_sp == 1) $('cost_price_'+item_id).value = json['selling_price'][sid];
					$('selling_price_'+item_id).value = json['selling_price'][sid];
				}
				
				if(allow_edit_selling_price)    $('selling_price_'+item_id).readOnly = false;
				else    $('selling_price_'+item_id).readOnly = true;
			}

			if(consignment_modules && masterfile_branch_region && consignment_multiple_currency && document.f_a['ci_branch_id'] != undefined){
				if($('new_sheets')!=undefined) foreign_variable_handler(true);
			}else{
				calc_all_items();
			}*/

			if(json['item_list']){
				for(var i=0; i<spans.length; i++){
					var sid = spans[i].id.split(',')[1];
					var item_id = spans[i].id.split(',')[2];
					
					var inp_selling_price = $('selling_price_'+item_id);
					var inp_cost_price = $('cost_price_'+item_id);

					if(json['item_list'][item_id]){
						inp_selling_price.value = json['item_list'][item_id]['selling_price'];
						inp_cost_price.value = json['item_list'][item_id]['cost_price'];

						if(!json['item_list'][item_id]['item_discount'] || json['item_list'][item_id]['item_discount']['value']){
		                    $('row_discount,'+item_id).update('0');
		                    $('input_discount_per,'+item_id).value = '0';
						}else{
		                    $('row_discount,'+item_id).update(json['item_list'][item_id]['item_discount']['value']);
							$('input_discount_per,'+item_id).value = json['item_list'][item_id]['item_discount']['value'];
						}

						// stock balance
						$('stock_balance,'+item_id).value = json['item_list'][item_id]['stock_balance'];

						if(hasforeign){
							// foreign cost price
							document.f_a['foreign_cost_price['+item_id+']'].value = json['item_list'][item_id]['foreign_cost_price'];
						}

						if(is_under_gst){
							// display cost price
							document.f_a['display_cost_price['+item_id+']'].value = json['item_list'][item_id]['display_cost_price'];	
						}

						// display cost price is inclusive
						document.f_a['display_cost_price_is_inclusive['+item_id+']'].checked = json['item_list'][item_id]['is_sku_inclusive'] == 'yes' ? true : false;
					}


					// allow edit selling price
					if(allow_edit_selling_price)    inp_selling_price.readOnly = false;
					else    inp_selling_price.readOnly = true;

					// recalc row
					CI_MODULE.item_row_changed(item_id);
				}
			}
		}
	});
}

change_discount = function(ele){
    var discount = ele.value.trim();
    var discount_format = /^\d+(\.\d+){0,1}(\+\d+(\.\d+){0,1}){0,1}$/;
	if(!discount_format.test(discount)){
        ele.value = '';
        discount = '';
	}
	
    //ele.value = round(ele.value,1);
    // found if discount more than 100%, set it become maximum 100% 
	if(ele.value != '' && ele.value > 100) ele.value = 100;
	if(ele.id=='input_discount_percent'){
		$('span_branch_discount_per').update(ele.value);
		recal_total();
	}
	else{
		calc_all_items();
	}
}

function curtain_clicked(){
	$('div_multi_add').hide();
}

function open_multi_add(){
	var all_li = $$('#autocomplete_sku_choices li');
	var sku_item_id_list = [];

	for(var i=0; i<all_li.length; i++){
		var li_title = all_li[i].title;
		if(!li_title)  continue;
		var sid = li_title.split(',')[0];

		sku_item_id_list.push(sid);
	}

	if(sku_item_id_list.length<=0){
        alert('Nothing to add.');
		return false;
	}
	
	var ci_branch_id = $('delivery_branches').value;
	var btn_submit_multi = $('btn_submit_multi');
	
	curtain(true);
	btn_submit_multi.value = 'Add';
	btn_submit_multi.disabled = true;
	
	$('div_multi_add').show();
	center_div('div_multi_add');
	$('div_multi_add_content').update(_loading_);
	var show_percentage = 0;
	if(document.f_a['show_per'].checked)    show_percentage = 1;
	new Ajax.Updater('div_multi_add_content',php_self,{
		parameters:{
			a: 'multi_add',
			'sku_item_id_list[]': sku_item_id_list,
			ci_branch_id: ci_branch_id,
			ci_id: document.f_a['id'].value,
			type: page_type,
			show_per: show_percentage
		},
		evalScripts: true,
		onComplete: function(){
			btn_submit_multi.disabled = false;
		}
	});
}

function selling_price_changed(ele){
	var ele_info = ele.title.split(',');
	var branch_id = ele_info[0];
	var item_id = ele_info[1];
	
	ele.value = round(ele.value, 3);
	row_recalc(ele,branch_id);
}

function do_reset(){
    if (check_login()) {
        document.f_do_reset['reason'].value = '';
        var p = prompt('Enter reason to Reset :');
        if (p==null || p.trim()=='' ) return false;
        document.f_do_reset['reason'].value = p;

        if(!confirm('Are you sure to reset?'))  return false;

        document.f_do_reset.submit();
    }
	return false;
}

function show_per_changed(){
	
	var show_per = document.f_a['show_per'].checked ? 1 : 0;
	if(!$('new_sheets'))    return;
	
	if(show_per){
	    $('span_show_per_loading').update(_loading_);

		var params = $(document.f_a).serialize()+'&a=show_per_changed';
	    $(document.f_a['show_per']).disabled = true;
	    
		ajax_request(php_self, {
			'parameters': params,
			onComplete: function(e){
				$('span_show_per_loading').update('');
				eval("var json = "+e.responseText);
				var spans = $('ci_items').getElementsBySelector('span.sku_item_info');

				for(var i=0; i<spans.length; i++){
					var sid = spans[i].id.split(',')[1];
					var item_id = spans[i].id.split(',')[2];

					// update discount percentage if it is lost invoice
					//if(show_per){
	                    if(!json['item_discount'][sid]['value']){
		                    $('row_discount,'+item_id).update('0');
		                    $('input_discount_per,'+item_id).value = '0';
						}else{
		                    $('row_discount,'+item_id).update(json['item_discount'][sid]['value']);
							$('input_discount_per,'+item_id).value = json['item_discount'][sid]['value'];
						}

					//}
					$('price_type,'+item_id).value = json['item_discount'][sid]['price_type'];
					$('trade_discount_code,'+item_id).value = json['item_discount'][sid]['trade_discount_code'];
				}

				$(document.f_a['show_per']).disabled = false;
				calc_all_items();
			}
		});
	}else{
        $$('#new_sheets span.row_discount').each(function(ele){
			$(ele).update('0');
		});
		$$('#new_sheets input.row_discount').each(function(ele){
			$(ele).value = 0;
		});
		//$('input_discount_percent').value = '';
	    //$('span_branch_discount_per').update('');
		calc_all_items();
	}
}

foreign_variable_handler = function(need_recalc){
	if ($('ci_items') == undefined) return; // if no items, return
	
	var ci_branch_id = document.f_a['ci_branch_id'].value;

	if(!ci_branch_id || branch_currency_code[ci_branch_id] == ""){
		$('span_p_currency_code').update("RM");
		$('span_sp_currency_code').update("RM");
		$('span_sp_amt_currency_code').update("RM");
		$('span_amt_currency_code').update("RM");
	}else{
		$('span_p_currency_code').update(branch_currency_code[ci_branch_id]);
		$('span_sp_currency_code').update(branch_currency_code[ci_branch_id]);
		$('span_sp_amt_currency_code').update(branch_currency_code[ci_branch_id]);
		$('span_amt_currency_code').update(branch_currency_code[ci_branch_id]);
	}
	
	if(!consignment_multiple_currency || !ci_branch_id || branch_currency_code[ci_branch_id] == "" || branch_currency_code[ci_branch_id] == "RM" ){
		// is local
		document.f_a['exchange_rate'].readOnly = true;
		$('foreign_price').style.display = "none";
		$('foreign_ttl_amt').style.display = "none";
		$$("#new_sheets .foreign_cost_price").invoke("hide");
		$$("#new_sheets .row_foreign_amount").invoke("hide");
		$$("#new_sheets #td_sub_total_foreign_amount").invoke("hide");
		$$("#new_sheets .total_foreign_amount").invoke("hide");
		$$("#new_sheets #td_display_foreign_discount_amount").invoke("hide");
		var ttl_colspan = document.f_a['colspan_length'].value;
		$("td_sub_total").colSpan = float(ttl_colspan);
		$("td_discount").colSpan = float(ttl_colspan);
		$("td_total").colSpan = float(ttl_colspan)-1;
	}else{
		// is foreign
		document.f_a['exchange_rate'].readOnly = false;
		$('foreign_price').style.display = "";
		$('foreign_ttl_amt').style.display = "";
		$$("#new_sheets .foreign_cost_price").invoke("show");
		$$("#new_sheets .row_foreign_amount").invoke("show");
		$$("#new_sheets #td_sub_total_foreign_amount").invoke("show");
		$$("#new_sheets .total_foreign_amount").invoke("show");
		$$("#new_sheets #td_display_foreign_discount_amount").invoke("show");
		var ttl_colspan = document.f_a['colspan_length'].value;
		$("td_sub_total").colSpan = float(ttl_colspan)+1;
		$("td_discount").colSpan = float(ttl_colspan)+1;
		$("td_total").colSpan = float(ttl_colspan);
	}
	if(need_recalc != undefined) calc_all_items();
	//if(need_recalc != undefined) foreign_variable_recalc();
}

calc_all_items=function(){
	var e = $('ci_items').getElementsBySelector('tr');
	for(var i=0;i<e.length;i++){
		row_recalc(e[i],false);
	}
	recal_total();
}

function get_parent_tr_by_ele(ele){
	var parent_ele = ele

		while(parent_ele){    // loop parebt until it found the div contain group id
		    if(parent_ele.tagName.toLowerCase()=='tr'){
                if($(parent_ele).hasClassName('tr_ci_item_row')){    // found the div
					break;  // break the loop
				}
			}
			// still not found, continue to get from parent node
            parent_ele = parent_ele.parentNode;
		}
		
		if(!parent_ele) return 0;

		//var item_id = $(parent_ele).getAttribute('item_id');
		
		return parent_ele;
}

function check_has_foreign(){
	var hasforeign=(consignment_modules && masterfile_branch_region && consignment_multiple_currency && document.f_a['exchange_rate'] != undefined  && !document.f_a['exchange_rate'].readOnly)?1:0;
	if(hasforeign){
		if(branch_currency_code[document.f_a['ci_branch_id'].value] && branch_currency_code[document.f_a['ci_branch_id'].value] != "RM"){
		
		}else{
			hasforeign = 0;
		}
	}
	
	return hasforeign;
}

function row_recalc(obj,need_recalc){
	if(need_recalc==undefined) need_recalc=true;

	var hasforeign = check_has_foreign();
	//var parent=(obj.tagName.toLowerCase()=='tr')?obj:$(obj).up(1);
	var parent = get_parent_tr_by_ele(obj);
	
	var id = $(parent).id.replace('titem','');
	var fraction = parent.getElementsBySelector('input[id=uom_fraction'+id+']')[0].value;
	var qty_ctn = parent.getElementsBySelector('input[name="qty_ctn['+id+']"]')[0].value;
	var qty_pcs = parent.getElementsBySelector('input[name="qty_pcs['+id+']"]')[0].value;
	
	if(hasforeign){
		var exchange_rate = (document.f_a['exchange_rate'].value==0)?1:document.f_a['exchange_rate'].value;
		if(document.f_a['exchange_rate'].value <= 0) exchange_rate = 1;
		//var last_cost_id = $('cost_price_'+id);
		//var foreign_cost_price=parent.getElementsBySelector('input[name="foreign_cost_price['+id+']"]')[0];
		
		//if(foreign_cost_price.value == 0) foreign_cost_price.value = last_cost_id.value;
		//last_cost_id.value = round(foreign_cost_price.value*exchange_rate, 3);
		$('cost_price_'+id).readOnly = true;
		document.f_a['foreign_cost_price['+id+']'].readOnly = false;
		
		if(is_under_gst){
			document.f_a['display_cost_price['+id+']'].readOnly = true;
		}
			
		/*if(branch_currency_code[document.f_a['ci_branch_id'].value] && branch_currency_code[document.f_a['ci_branch_id'].value] != "RM"){
			//if(foreign_cost_price.value == 0) foreign_cost_price.value = last_cost_id.value;
			//last_cost_id.value = round(foreign_cost_price.value*exchange_rate, 3);
			last_cost_id.readOnly = true;
			foreign_cost_price.readOnly = false;
			
			if(is_under_gst){
				document.f_a['display_cost_price['+id+']'].readOnly = true;
			}
			
		}else{
			if(!branch_exchange_rate[document.f_a['ci_branch_id'].value] && foreign_cost_price.value > 0 && last_cost_id.value == 0) last_cost_id.value = foreign_cost_price.value;
			last_cost_id.readOnly = false;
			foreign_cost_price.readOnly = true;
			
			if(is_under_gst){
				document.f_a['display_cost_price['+id+']'].readOnly = false;
			}
		}*/
	}else{
		$('cost_price_'+id).readOnly = false;
		if(document.f_a['foreign_cost_price['+id+']'])	document.f_a['foreign_cost_price['+id+']'].readOnly = true;
		
		if(is_under_gst){
			document.f_a['display_cost_price['+id+']'].readOnly = false;
		}
	}
	var cost_price=$('cost_price_'+id).value;	
		
	if(fraction>1){
		var old_pcs=float(qty_pcs);
		var new_pcs=float(old_pcs%fraction);
		var remain=float(old_pcs)-new_pcs;
		var ctn=(remain/fraction)+float(qty_ctn);
		parent.getElementsBySelector('input[name="qty_pcs['+id+']"]')[0].value=round(new_pcs);
		parent.getElementsBySelector('input[name="qty_ctn['+id+']"]')[0].value=round(ctn);
	}
	
	var display_cost_price_is_inclusive = 0;
	var gst_rate = 0;
	if(is_under_gst){
		display_cost_price_is_inclusive = document.f_a['display_cost_price_is_inclusive['+id+']'].checked;
		gst_rate = float(document.f_a["gst_rate["+id+"]"].value);
	}
	var row_qty=int((float(qty_ctn)*fraction)+(float(qty_pcs)));
	var row_amount=row_qty*(cost_price/fraction);	
	var row_selling = float($('selling_price_'+id).value/fraction)*row_qty;
	
	var item_discount = parent.getElementsBySelector('input[name="discount_per['+id+']"]')[0].value;
	var discount_selling_price = ($('input_discount_selling_price_percent'))?$('input_discount_selling_price_percent').value:0; //Discount Selling Price
	var discount_item_row = ($('input_discount_item_row_percent'))?$('input_discount_item_row_percent').value:0; //Discount Item Row
	var row_amt=row_amount;
	ttl_disc_amt = row_foreign_disc_amt = 0;
	if(discount_selling_price){
		var disc=discount_selling_price.split("+");
		for(i=0;i<disc.length;i++){
			var discount_amt = row_amt*(float(disc[i])/100);
			row_amt -= discount_amt;
			ttl_disc_amt += float(discount_amt);
		}
		//row_amt=row_amount;
	}
	
	//console.log('discount_item_row: '+discount_item_row);
	if(discount_item_row){
		var disc=discount_item_row.split("+");
		for(i=0;i<disc.length;i++){
			var discount_amt = row_amt*(float(disc[i])/100);
			row_amt -= discount_amt;
			ttl_disc_amt += float(discount_amt);
		}
	}
	
	if(item_discount){
		var disc=item_discount.split("+");
		for(i=0;i<disc.length;i++){			
			var discount_amt = row_amt*(float(disc[i])/100);
			//row_amount -= discount_amt;
			row_amt-=discount_amt;
			ttl_disc_amt += float(discount_amt);
		}
	}
	
	$('inp_item_disc_amt-'+id).value = round(ttl_disc_amt, 2);
	$('row_qty'+id).innerHTML=float(row_qty);
	$('row_amount'+id).innerHTML=round(row_amt,2);
	$('row_selling'+id).innerHTML = round(row_selling,2);
	
	if(hasforeign){
		var cost_price=document.f_a['foreign_cost_price['+id+']'].value;
		if(is_under_gst){
			if(display_cost_price_is_inclusive){
				cost_price = cost_price / (100+gst_rate) * 100;
			}
		}
		row_foreign_amount=row_qty*(cost_price/fraction);
			
		if(discount_selling_price){
			var disc=discount_selling_price.split("+");
			for(i=0;i<disc.length;i++){
				var discount_amt = row_foreign_amount*(float(disc[i])/100);
				row_foreign_amount -= discount_amt;
				row_foreign_disc_amt += float(discount_amt);
			}
		}
				
		if(discount_item_row){
			var disc=discount_item_row.split("+");
			for(i=0;i<disc.length;i++){
				var discount_amt = row_foreign_amount*(float(disc[i])/100);
				row_foreign_amount -= discount_amt;
				row_foreign_disc_amt += float(discount_amt);
			}
		}
		
		if(item_discount){
			var disc=item_discount.split("+");
			for(i=0;i<disc.length;i++){
				var discount_amt = row_foreign_amount*(float(disc[i])/100);
				row_foreign_amount -= discount_amt;
				row_foreign_disc_amt += float(discount_amt);
			}
		}
		
		//row_foreign_amount = round(row_foreign_amount, 2);
		document.f_a["item_foreign_amt["+id+"]"].value = round(row_foreign_amount,2);
		var row_foreign_gst = 0;
		if (is_under_gst) {	
			row_foreign_gst = float(row_foreign_amount*gst_rate/100);
			document.f_a["item_foreign_gst["+id+"]"].value = round(row_foreign_gst,2);
			
		}
		row_foreign_amount = float(row_foreign_amount) + float(row_foreign_gst);
				
		$('row_foreign_amount'+id).innerHTML=round(row_foreign_amount,2);
		document.f_a["item_foreign_disc_amt["+id+"]"].value = round(row_foreign_disc_amt,2);
		document.f_a["item_foreign_gst_amt["+id+"]"].value = round(row_foreign_amount,2);
	}
	
	
	var row_gst = 0;
	var row_gst_amt = 0;
	
	$('row_amount'+id).innerHTML=round(row_amt,2);
	if(is_under_gst){
		row_gst = float(row_amt*gst_rate/100);
	}

	row_gst_amt = float(round(row_amt+row_gst,2));
	var row_amt_rounded = float(round(row_amt, 2));
	row_gst = float(round(row_gst_amt-row_amt_rounded,2));
	
	if(is_under_gst){
		$('item_gst_amt'+id).update(row_gst_amt.toFixed(2));
		document.f_a["item_gst["+id+"]"].value = round(row_gst,2);
		$('row_gst'+id).update(round(row_gst, 2));
	}
	
	document.f_a["item_gst_amt["+id+"]"].value = round(row_gst_amt,2);
	document.f_a["item_amt["+id+"]"].value = round(row_amt, 2);
	
	document.f_a["item_amt2["+id+"]"].value = round(row_amt, 2);
	document.f_a["item_gst_amt2["+id+"]"].value = round(row_gst_amt,2);
	document.f_a["item_disc_amt2["+id+"]"].value = 0;
	if(is_under_gst){
		document.f_a["item_gst2["+id+"]"].value = round(row_gst,2);
	}
	if(need_recalc) recal_total();
}

function recal_total(){	
	var total_ctn=0,
	total_pcs=0,
	total_ctn=0,
	total_pcs=0,
	total_selling=0;
	var discount_perc = "";
	var disc_count = 0;
	
	var sub_total_gross_amt = 0;
	var sub_total_gst_amt = 0;
	var sub_total_amt = 0;
	
	var sub_total_foreign_gross_amt = 0;
	var sub_total_foreign_gst_amt = 0;
	var sub_total_foreign_amt = 0;
	
	// check got foreign or not
	var hasforeign = check_has_foreign();
	
	var tr_item_list = $('ci_items').getElementsBySelector('tr.tr_ci_item_row');
	for(var i=0,item_len = tr_item_list.length;i<item_len;i++){
		var tr=tr_item_list[i];
		var id=tr.id.replace('titem','');
		
		var qty_ctn = float($(tr).getElementsBySelector('input[name="qty_ctn['+id+']"]')[0].value);
		var qty_pcs = float($(tr).getElementsBySelector('input[name="qty_pcs['+id+']"]')[0].value);
		var row_selling = float($(tr).getElementsBySelector('span[id="row_selling'+id+'"]')[0].innerHTML);
		var row_amount = float(round(document.f_a['item_amt['+id+']'].value,2));
		var row_gst = 0;
		if(is_under_gst)	row_gst = float(round(document.f_a['item_gst['+id+']'].value, 2));
		var row_gst_amt = float(round(document.f_a['item_gst_amt['+id+']'].value, 2));
		
		total_ctn+=qty_ctn;
		total_pcs+=qty_pcs;		
		total_selling+=row_selling;
		
		if(hasforeign){
			var row_foreign_gross_amount=float(round(document.f_a['item_foreign_amt['+id+']'].value, 2));
			var row_foreign_gst = 0;
			if(is_under_gst)	row_foreign_gst = float(round(document.f_a['item_foreign_gst['+id+']'].value, 2));
			var row_foreign_gst_amount = float(round(document.f_a['item_foreign_gst_amt['+id+']'].value, 2));
			
			sub_total_foreign_gross_amt += row_foreign_gross_amount;
			sub_total_foreign_gst_amt += row_foreign_gst;
			sub_total_foreign_amt += row_foreign_gst_amount;
		}
		
		sub_total_gross_amt += row_amount;
		sub_total_gst_amt += row_gst;
		sub_total_amt += row_gst_amt;
		
		
	}
	// normal
	var gross_discount_amount = 0;
	var sheet_gst_discount = 0;
	var discount_amount = 0;
	
	var total_gross_amt = sub_total_gross_amt;
	var total_gst_amt = sub_total_gst_amt;
	var total_amount = sub_total_amt;
	
	// foreign
	var gross_foreign_discount_amount = 0;
	var sheet_foreign_gst_discount = 0;
	var foreign_discount_amount = 0;
	
	var total_foreign_gross_amt = sub_total_foreign_gross_amt;
	var total_foreign_gst_amt = sub_total_foreign_gst_amt;
	var total_foreign_amount = sub_total_foreign_amt;
	
	// check sheet discount
	var discount = $('input_discount_percent').value;
	var p;
	if(discount){
		var disc=discount.split("+");
		var tmp_amt = total_amount;
		for(i=0;i<disc.length;i++){
			var disc_amt = float(tmp_amt*(disc[i]/100));
		    discount_amount += disc_amt;
			tmp_amt -= disc_amt;
			
			discount_perc += disc[i]+"%";
			disc_count++;
			if(disc.length != disc_count) discount_perc += "+";
		}		
        $('tr_discount_amount').show();
		
		p = (discount_amount * 100) / total_amount;
		
		discount_amount = float(round(discount_amount,2));
		if(discount_amount){
			total_amount -= discount_amount;
		}
		gross_discount_amount = float(round(total_gross_amt * p /100,2));
		total_gross_amt -= gross_discount_amount;

		sheet_gst_discount = float(round(discount_amount-gross_discount_amount, 2));
		total_gst_amt = float(round(total_gst_amt-sheet_gst_discount,2));
		
		if(hasforeign){
			foreign_discount_amount = float(round(get_discount_amt(sub_total_foreign_amt, discount_perc),2));
			total_foreign_amount -= foreign_discount_amount;
			
			gross_foreign_discount_amount = float(round(get_discount_amt(sub_total_foreign_gross_amt, discount_perc),2));
			total_foreign_gross_amt -= gross_foreign_discount_amount;
			
			sheet_foreign_gst_discount = float(round(foreign_discount_amount-gross_foreign_discount_amount,2));
			total_foreign_gst_amt = float(round(total_foreign_gst_amt-sheet_foreign_gst_discount,2));
		}
	}else{
		$('tr_discount_amount').hide();
	}
	
	// sub total
	$('t_ctn').innerHTML = round(total_ctn);
	$('t_pcs').innerHTML = round(total_pcs);	
	$('total_ctn').value=round(total_ctn);
	$('total_pcs').value=round(total_pcs);
	$('td_sub_total_selling').innerHTML = round(total_selling,2);
	$('total_selling').value=round(total_selling,2);
		
	document.f_a['sub_total_gross_amt'].value = round(sub_total_gross_amt, 2);
	$('td_sub_total_amount').innerHTML = round(sub_total_gross_amt,2);
	
	if(is_under_gst)	$('td_sub_total_gst').update(sub_total_gst_amt.toFixed(2));
	
	$('sub_total_amt').value=round(sub_total_amt,2);
	if(is_under_gst)	$('td_sub_total_gst_amount').update(sub_total_amt.toFixed(2));
	
	// foreign
	if(hasforeign){
		document.f_a['sub_total_foreign_gross_amt'].value = round(sub_total_foreign_gross_amt, 2);
		
		$('td_sub_total_foreign_amount').innerHTML = round(sub_total_foreign_amt,2);
		
		$('sub_total_foreign_amt').value=round(sub_total_foreign_amt, 2);
	}
	
	// discount
	document.f_a['gross_discount_amount'].value = round(gross_discount_amount, 2);
	$('td_display_discount_amount').innerHTML = round(gross_discount_amount*-1,2);
	
	document.f_a['sheet_gst_discount'].value = round(sheet_gst_discount,2);
	if(is_under_gst)	$('td_sheet_discount_gst').update((sheet_gst_discount*-1).toFixed(2));
	
	document.f_a['discount_amount'].value = round(discount_amount,2);
	if(is_under_gst)	$('td_sheet_discount_gst_amount').update((discount_amount*-1).toFixed(2));
	
	if(hasforeign){
		document.f_a['gross_foreign_discount_amount'].value = round(gross_foreign_discount_amount, 2);
		
		document.f_a['sheet_foreign_gst_discount'].value = round(sheet_foreign_gst_discount,2);
		
		document.f_a['foreign_discount_amount'].value = round(foreign_discount_amount,2);
		$('td_display_foreign_discount_amount').update((foreign_discount_amount*-1).toFixed(2));
	}
	
	// total
	document.f_a['total_gross_amt'].value = round(total_gross_amt,2);
	$('display_total_amount').innerHTML = round(total_gross_amt,2);
	
	document.f_a['total_gst_amt'].value = round(total_gst_amt,2);
	if(is_under_gst)	$('td_total_gst').update(total_gst_amt.toFixed(2));
	
	document.f_a['total_amount'].value = round(total_amount,2);
	if(is_under_gst)	$('td_total_gst_amt').update(total_amount.toFixed(2));
	
	if(hasforeign){
		document.f_a['total_foreign_gross_amt'].value = round(total_foreign_gross_amt, 2);
		
		document.f_a['total_foreign_gst_amt'].value = round(total_foreign_gst_amt,2);
		
		document.f_a['total_foreign_amount'].value = round(total_foreign_amount,2);
		$('display_total_foreign_amount').update(total_foreign_amount.toFixed(2));
	}
	
	// calculate amt 2
	var remaining_gross_discount_amount = gross_discount_amount;
	var remaining_sheet_gst_discount = sheet_gst_discount;
	var remaining_sheet_discount_amt = discount_amount;

	// loop for each row to calculate gross amt2, gst amt2, line total amt2
	for(var i=0,item_len = tr_item_list.length;i<item_len;i++){
		var item_id=tr_item_list[i].id.replace('titem','');
		
		var line_gross_amt = float(document.f_a["item_amt["+item_id+"]"].value);
		
		var gst_rate = 0;
		var line_gst_amt = 0;
		if(is_under_gst){
			gst_rate = float(document.f_a["gst_rate["+item_id+"]"].value);
			line_gst_amt = float(document.f_a["item_gst["+item_id+"]"].value);
		}		
		
		var line_amt = float(document.f_a["item_gst_amt["+item_id+"]"].value);

		var line_gross_amt2 = line_gross_amt;
		var line_gst_amt2 = line_gst_amt;
		var line_amt2 = line_amt;
		var item_discount_amount2 = 0;

		if (p!= undefined) {
			line_amt2 = line_amt * ((100 - p) / 100);
			line_gross_amt2 = line_amt2 / ((100 + gst_rate) / 100);
			line_gst_amt2 = line_amt2 - line_gross_amt2;

			var line_amt2_rounded = float(round(line_amt2 ,2));
			var line_gross_amt2_rounded = float(round(line_gross_amt2 ,2));
			line_gst_amt2 = float(round(line_amt2_rounded-line_gross_amt2_rounded,2));
			
			item_discount_amount2 = line_amt - line_amt2_rounded;
		}

		line_gross_amt2 = float(round(line_gross_amt2,2));
		line_gst_amt2 = float(round(line_gst_amt2,2));
		line_amt2 = float(round(line_amt2,2));
		item_discount_amount2 = float(round(item_discount_amount2,2));
		
		remaining_gross_discount_amount = float(round(remaining_gross_discount_amount - (line_gross_amt - line_gross_amt2), 2));
		remaining_sheet_gst_discount = float(round(remaining_sheet_gst_discount - (line_gst_amt - line_gst_amt2), 2));
		remaining_sheet_discount_amt = float(round(remaining_sheet_discount_amt - (item_discount_amount2), 2));
		
		//console.log('RM: item_discount_amount2: '+item_discount_amount2+', remaining_sheet_discount_amt: '+remaining_sheet_discount_amt);
		
		if(i == item_len-1){
			if(remaining_gross_discount_amount != 0){
				line_gross_amt2 -= remaining_gross_discount_amount;
				remaining_gross_discount_amount = 0;
			}
			if(remaining_sheet_gst_discount != 0){
				line_gst_amt2 -= remaining_sheet_gst_discount;
				remaining_sheet_gst_discount = 0;
			}
			if(remaining_sheet_discount_amt != 0){
				line_amt2 -= remaining_sheet_discount_amt;
				item_discount_amount2 += remaining_sheet_discount_amt;
				remaining_sheet_discount_amt = 0;
			}
		}
		//console.log('RM: item_discount_amount2: '+item_discount_amount2);
		
		document.f_a["item_amt2["+item_id+"]"].value = round(line_gross_amt2,2);
		if(is_under_gst)	document.f_a["item_gst2["+item_id+"]"].value = round(line_gst_amt2,2);
		document.f_a["item_gst_amt2["+item_id+"]"].value = round(line_amt2,2);
		document.f_a["item_disc_amt2["+item_id+"]"].value = round(item_discount_amount2,2);
	}
		
	if(hasforeign){
		var remaining_total_foreign_gross_discount_amt = gross_foreign_discount_amount;
		var remaining_sheet_foreign_gst_discount = sheet_foreign_gst_discount;
		var remaining_total_foreign_discount_amt = foreign_discount_amount;
		
		// loop for each row to calculate gross amt2, gst amt2, line total amt2
		for(var i=0,item_len = tr_item_list.length;i<item_len;i++){
			var item_id=tr_item_list[i].id.replace('titem','');

			var gst_rate = 0;
			var line_foreign_gross_amt = float(document.f_a["item_foreign_amt["+item_id+"]"].value);
			var line_foreign_gst_amt = 0;
			var line_foreign_amt = float(document.f_a["item_foreign_gst_amt["+item_id+"]"].value);
			
			if(is_under_gst){
				gst_rate = float(document.f_a["gst_rate["+item_id+"]"].value);
				line_foreign_gst_amt = float(document.f_a["item_foreign_gst["+item_id+"]"].value);
			}
			
			var line_foreign_gross_amt2 = line_foreign_gross_amt;
			var line_foreign_gst_amt2 = line_foreign_gst_amt;
			var line_foreign_amt2 = line_foreign_amt;
			var item_foreign_discount_amount2 = 0;

			if (p) {
				line_foreign_amt2 = line_foreign_amt * ((100 - p) / 100);
				line_foreign_gross_amt2 = line_foreign_amt2 / ((100 + gst_rate) / 100);
				
				var line_foreign_amt2_rounded = round(line_foreign_amt2, 2);
				var line_foreign_gross_amt2_rounded = round(line_foreign_gross_amt2, 2);
				
				line_foreign_gst_amt2 = line_foreign_amt2_rounded - line_foreign_gross_amt2_rounded;

				item_foreign_discount_amount2 = float(round(line_foreign_amt - line_foreign_amt2_rounded, 2));
			}
			
			line_foreign_gross_amt2 = float(round(line_foreign_gross_amt2,2));
			line_foreign_gst_amt2 = float(round(line_foreign_gst_amt2,2));
			line_foreign_amt2 = float(round(line_foreign_amt2,2));
			item_foreign_discount_amount2 = float(round(item_foreign_discount_amount2,2));
			
			remaining_total_foreign_gross_discount_amt = float(round(remaining_total_foreign_gross_discount_amt - (line_foreign_gross_amt - line_foreign_gross_amt2), 2));
			remaining_sheet_foreign_gst_discount = float(round(remaining_sheet_foreign_gst_discount - (line_foreign_gst_amt - line_foreign_gst_amt2), 2));
			remaining_total_foreign_discount_amt = float(round(remaining_total_foreign_discount_amt - (item_foreign_discount_amount2), 2));
			
			//console.log('item_foreign_discount_amount2: '+item_foreign_discount_amount2+',remaining_total_foreign_discount_amt: '+remaining_total_foreign_discount_amt);
			if(i == item_len-1){
				if(remaining_total_foreign_gross_discount_amt != 0){
					line_foreign_gross_amt2 -= remaining_total_foreign_gross_discount_amt;
					remaining_total_foreign_gross_discount_amt = 0;
				}
				if(remaining_sheet_foreign_gst_discount != 0){
					line_foreign_gst_amt2 -= remaining_sheet_foreign_gst_discount;
					remaining_sheet_foreign_gst_discount = 0;
				}
				if(remaining_total_foreign_discount_amt != 0){
					line_foreign_amt2 -= remaining_total_foreign_discount_amt;
					item_foreign_discount_amount2 += remaining_total_foreign_discount_amt;
					remaining_total_foreign_discount_amt = 0;
				}
			}
			
			document.f_a["item_foreign_amt2["+item_id+"]"].value = round(line_foreign_gross_amt2,2);
			
			if(is_under_gst){
				document.f_a["item_foreign_gst2["+item_id+"]"].value = round(line_foreign_gst_amt2,2);
			}
			
			document.f_a["item_foreign_gst_amt2["+item_id+"]"].value = round(line_foreign_amt2,2);
			document.f_a["item_foreign_disc_amt2["+item_id+"]"].value = round(item_foreign_discount_amount2, 2);
		}
	}
}

// function when do date is changed
function check_gst_date_changed(){
	var allow_gst = false;

	// gst is not enable
	if(!enable_gst)	return;

	// gst is active and branch got register
	if(gst_is_active && branch_gst_register_no){
		if(skip_gst_validate){
			allow_gst = true;
		}else{
			// got gst start date
			if(global_gst_start_date && branch_gst_start_date){
				// get Date
				var ci_date = document.f_a["ci_date"].value.trim();

				if(ci_date){
					// check Date
					if(strtotime(ci_date) >= strtotime(global_gst_start_date) && strtotime(ci_date) >= strtotime(branch_gst_start_date)){
						allow_gst = true;
					}
				}
			}
		}
	}

	if(allow_gst){
		// date have gst
		if(!is_under_gst)	need_refresh_sheet();
	}else{
		// date no gst
		if(is_under_gst)	need_refresh_sheet();
	}
}

// function when user change gst dropdown selection
function on_item_gst_changed(sel, item_id){
	// update the selected gst
	update_selected_gst(item_id);

	// recalculate row
	row_recalc(sel);
}

// function to update gst id/code/rate
function update_selected_gst(item_id){
	document.f_a["gst_id["+item_id+"]"].value = "";
	document.f_a["gst_code["+item_id+"]"].value = "";
	document.f_a["gst_rate["+item_id+"]"].value = "";
	document.f_a["gst_indicator["+item_id+"]"].value = "";

	var sel = document.f_a['item_gst_sel['+item_id+']'];

	if(sel.selectedIndex >= 0){
		// got select
		var opt = sel.options[sel.selectedIndex];
		var gst_id = $(opt).readAttribute("gst_id");
		var gst_code = $(opt).readAttribute("gst_code");
		var gst_rate = $(opt).readAttribute("gst_rate");
		var gst_indicator = $(opt).readAttribute("gst_indicator");

		document.f_a["gst_id["+item_id+"]"].value = gst_id;
		document.f_a["gst_code["+item_id+"]"].value = gst_code;
		document.f_a["gst_rate["+item_id+"]"].value = gst_rate;
		document.f_a["gst_indicator["+item_id+"]"].value = gst_indicator;
	}
}

function need_refresh_sheet(){
    if (check_login()) {
        document.f_a.a.value = "refresh";
        document.f_a.target = "";
        document.f_a.submit();
    }
}

// function when do date changed
function on_date_changed(){
	// get the object
	var inp = document.f_a['ci_date'];
	// check max/min limit
	upper_lower_limit(inp);
	// check gst
	if(enable_gst)	check_gst_date_changed();
}

function on_export_clicked(obj){
	if(obj.checked == true){ // lock all tax code selection
		var tr_gst_code_list = $$('#ci_items select.item_gst_slt');
		var all_rows = tr_gst_code_list.length;

		if(all_rows > 0){
			$A(tr_gst_code_list).each(
				function (r,idx){
					var item_id = $(r).readAttribute('item_id');
					$(r).value = gst_export;
					update_selected_gst(item_id);
					r.disabled = true;
					row_recalc(r);
				}
			);
		}
	}else{
		var tr_gst_code_list = $$('#ci_items select.item_gst_slt');
		var all_rows = tr_gst_code_list.length;

		if(all_rows > 0){
			$A(tr_gst_code_list).each(
				function (r,idx){
					r.disabled = false;
				}
			);
		}
	}
}

function toggle_process_gst_price(id){
	showdiv('div_process_gst_price');
	center_div('div_process_gst_price');
	$("pgp_item_id").value = id;
	
	// update label for gst rate 
	var gst_rate = document.f_a['gst_rate['+id+']'].value;
	if(gst_rate > 0) $("span_pgp_gst_rate").update(gst_rate);
	else $("span_pgp_gst_rate").update('0');
	$("pgp_gst_price").value = "";
	$("pgp_gst").value = "";
	$("pgp_price").value = "";
	$("pgp_gst_price").focus();
}

function process_gst_price(obj){
	extractNumber(obj, 2, 0);
	
	var gst_price = float($("pgp_gst_price").value);
	var id = $("pgp_item_id").value;
	var gst_rate = float(document.f_a['gst_rate['+id+']'].value);
	
	var gst = float(round(gst_price / float(gst_rate+100) * gst_rate, 2));
	$("pgp_gst").value = round(gst, 2);
	$("pgp_price").value = round(gst_price - gst, 2);
}

function process_gst_price_clicked(){
	hidediv('div_process_gst_price');
	
	var id = $("pgp_item_id").value;
	document.f_a['cost_price['+id+']'].value = $("pgp_price").value;
	row_recalc(document.f_a['cost_price['+id+']']);
}

function price_onkeypress(event){
	if (event == undefined) event = window.event;
	if(event.keyCode==13){  // enter
		process_gst_price_clicked();
	}
}

/*
foreign_variable_recalc = function(){
	if(document.f_a['exchange_rate'] == undefined) return;

	var exchange_rate = document.f_a['exchange_rate'].value;
	if(document.f_a['exchange_rate'].value == 0){
		exchange_rate = 1;
	}

	var e = $('ci_items').getElementsByClassName('uom');
	var foreign_cost = "";
	var total_foreign_amount = "";
	var cost = "";
	var last_id = "";
	var item_fraction=new Array();
	var item_foreign_cost=new Array();
	var item_qty=new Array();
	
	var row_ctn=new Array();
	var row_pcs=new Array();

	for(var i=0;i<e.length;i++){
		
		var temp_1 =new RegExp('^cost_price_');
		if (temp_1.test(e[i].id)){ // is cost
			if(cost){
				e[i].value = cost;
				cost = "";
			}

			last_cost_id = e[i];
		}

		var temp_2 =new RegExp('^foreign_cost_price_');
		if (temp_2.test(e[i].id)){
			var line = e[i].title.split(",");
			if(foreign_cost){ // is from selling or other but not cost
				e[i].value = foreign_cost;
				foreign_cost = "";
			}
			if(branch_currency_code[document.f_a['ci_branch_id'].value] && branch_currency_code[document.f_a['ci_branch_id'].value] != "RM"){
				if(e[i].value == 0) e[i].value = last_cost_id.value;
				last_cost_id.value = round(e[i].value*exchange_rate, 3);
				last_cost_id.readOnly = true;
				e[i].readOnly = false;
			}else{
				if(!branch_exchange_rate[document.f_a['ci_branch_id'].value] && e[i].value > 0 && last_cost_id.value == 0) last_cost_id.value = e[i].value;
				last_cost_id.readOnly = false;
				e[i].readOnly = true;
			}

			item_foreign_cost[line[1]] = float(e[i].value);
		}
		
 		var temp_3 = new RegExp('^qty_ctn');
		if (temp_3.test(e[i].id)){
			var line = e[i].title.split(",");
			if(!row_ctn[line[1]]){
				row_ctn[line[1]]=0;
			}
			row_ctn[line[1]]=float(e[i].value);
		}
		
 		var temp_4 = new RegExp('^qty_pcs');
		if (temp_4.test(e[i].id)){
			var line = e[i].title.split(",");
			if(!row_pcs[line[1]]){
				row_pcs[line[1]]=0;
			}
			row_pcs[line[1]]=float(e[i].value);
		}

		var temp_5 = new RegExp('^uom_fraction');
		if (temp_5.test(e[i].id)) {
			item_fraction[e[i].title]=float(e[i].value);
		}
		
  		var temp_6 = new RegExp('^row_qty');
		if (temp_6.test(e[i].id)) {
			var line =e[i].title.split(",");
			item_qty[line[1]]=float(e[i].innerHTML);
		}

 		var temp_7 =new RegExp('^row_foreign_amount');
		if (temp_7.test(e[i].id)){
			var line =e[i].title.split(",");
			item_id=line[1];
			row_foreign_total=round(item_foreign_cost[item_id]*item_qty[item_id]/item_fraction[item_id],2);
			
			// calculate row discount if it is lost invoice
			var discount = $('input_discount_per,'+item_id).value;
			var disc1 = float(discount.split("+")[0]);
			var disc2 = 0;
			if(discount.split("+").length>1)	disc2 = float(discount.split("+")[1]);

			if(disc1){  // sheet discount 1
				foreign_discount_amt = row_foreign_total*(disc1/100);
				row_foreign_total -= foreign_discount_amt;
			}
			if(disc2){  // further discount
				foreign_discount_amt = row_foreign_total*(disc2/100);
				row_foreign_total -= foreign_discount_amt;
			}
			row_foreign_total = round(row_foreign_total,2);
			
			$('row_foreign_amount'+item_id).innerHTML=row_foreign_total;
			total_foreign_amount+=float(row_foreign_total);
		}
	}

	$('display_total_foreign_amount').innerHTML=round(total_foreign_amount,2);
	document.f_a['total_foreign_amount'].value=round(total_foreign_amount,3);
	
	calc_all_items();
}
function select_type(val){	

	if(val=='2'){
		$('delivery_open').style.display='';
		$('delivery_branches').style.display='none';
		$('delivery_branches').disabled=true;
	}
	else{
		$('oi_address').value='';
		$('oi_name').value='';
		$('delivery_branches').style.display='';
		$('delivery_branches').disabled=false;
		$('delivery_open').style.display='none';
	}	
	
	change_lost_inv_branch();
}

function row_recalc(id,branch){
    
	var row_ctn=0, total_ctn=0;
	var row_pcs=0, total_pcs=0;
	var branch_qty=0;
	var total_qty=0;
	var total_amount=0;
	var branch_fraction=new Array();
	var branch_ctn=new Array();
	var branch_pcs=new Array();
	var ctn=new Array();
	
	var row_selling = 0;
	var total_selling = 0;
	var discount_amount = 0;
	
	// if no items, return
	if ($('ci_items') == undefined) return;
	
	var e = $('ci_items').getElementsByClassName('uom');
	for(var i=0;i<e.length;i++)	{
		
		var temp_6=new RegExp('^qty_ctn');
		if (temp_6.test(e[i].id)){
			var line =e[i].title.split(",");
			ctn[line[0]]=0;
			fraction=$('uom_fraction'+id).value;
			if(line[1]==id && fraction>1){
				old_pcs=float($('qty_pcs'+id+'_'+line[0]).value);
				new_pcs=float(old_pcs%fraction);
				remain=float(old_pcs)-new_pcs;
				ctn=(remain/fraction)+float(e[i].value);
				$('qty_pcs'+id+'_'+line[0]).value=round(new_pcs);
				e[i].value=round(ctn);	
			}
		}
		
 		var temp_1 =new RegExp('^qty_ctn');
		if (temp_1.test(e[i].id)) {
			var line =e[i].title.split(",");
			if(line[1]==id){			
				row_ctn+=float(e[i].value);
				if(line[0]==branch){
					branch_ctn[line[0]]=float(e[i].value);
				}
			}
			total_ctn+=float(e[i].value);
		}		
		
 		var temp_2 =new RegExp('^qty_pcs');
		if (temp_2.test(e[i].id)) {
			var line =e[i].title.split(",");
			if(line[1]==id){
				row_pcs+=float(e[i].value);
				if(line[0]==branch){
					branch_pcs[line[0]]=float(e[i].value);
				}
			}
			total_pcs+=float(e[i].value);
		}
	
		var temp_20 =new RegExp('^uom_fraction');
		if (temp_20.test(e[i].id)) {
			branch_fraction[e[i].title]=float(e[i].value);
		}
		
		fraction=float(branch_fraction[id]);
		
		row_qty=int((row_ctn*fraction)+(row_pcs));
		$('row_qty'+id).innerHTML=float(row_qty);
		var old_cost=$('cost_price_'+id).value;
				
		row_amount=round(row_qty*(old_cost/fraction),2);
		// calculate row discount if it is lost invoice
		//if(show_per){
		//	var discount = float($('row_discount,'+id).innerHTML);
		//	var discount_per = float(discount*0.01);
		//	var discount_amount = row_amount*discount_per;
		//	row_amount = round(row_amount-discount_amount,2);
		//}
		
		$('row_amount'+id).innerHTML=round(row_amount,2);
		
  		var temp_5 =new RegExp('^row_qty');
		if (temp_5.test(e[i].id)) {
			total_qty+=float(e[i].innerHTML);
		}
		
  		var temp_6 =new RegExp('^row_amount');
		if (temp_6.test(e[i].id)) {
			total_amount+=float(e[i].innerHTML);
		}
	}
	
	//if(show_per){
	    var discount = $('input_discount_per,'+id).value;
		var disc1 = float(discount.split("+")[0]);
		var disc2 = 0;
		if(discount.split("+").length>1)	disc2 = float(discount.split("+")[1]);
	
	    if(disc1){  // sheet discount 1
		    discount_amt = row_amount*(disc1/100);
	        row_amount -= discount_amt;
		}
		if(disc2){  // further discount
		    discount_amt = row_amount*(disc2/100);
	        row_amount -= discount_amt;
		}

		row_amount = round(row_amount,2);
		$('row_amount'+id).innerHTML=round(row_amount,2);
	//}
	
	row_qty = int($('row_qty'+id).innerHTML);
	row_selling = float($('selling_price_'+id).value)*row_qty;
	$('row_selling'+id).innerHTML = round(row_selling,2);
	
	$('t_ctn').innerHTML=round(total_ctn);
	$('t_pcs').innerHTML=round(total_pcs);
	$('total_ctn').value=round(total_ctn);
	$('total_pcs').value=round(total_pcs);
	$('display_total_amount').innerHTML=round(total_amount,2);
	$('total_amount').value=round(total_amount,2);
	
	if(consignment_modules && masterfile_branch_region && consignment_multiple_currency) foreign_variable_recalc();
	recal_total();
}

recal_total = function (){
    //var discount_percent = float($('input_discount_percent').value);
    var discount = $('input_discount_percent').value;
	var disc1 = float(discount.split("+")[0]);
	var disc2 = 0;
	if(discount.split("+").length>1)	disc2 = float(discount.split("+")[1]);
	
    var total_amount = 0;
    var total_foreign_amount = 0;
    var sub_total_sell = 0;
    //var discount_amount = 0;
    var discount_amt = 0;
    var foreign_discount_amt = 0;
    var total_discount_amt = 0;
    var total_foreign_discount_amt = 0;
    
    var e = $('ci_items').getElementsBySelector("span.uom");
    for(var i=0; i<e.length; i++){
        if(e[i].id.indexOf('row_amount')==0) total_amount += float(e[i].innerHTML);
        if(e[i].id.indexOf('row_foreign_amount')==0) total_foreign_amount += float(e[i].innerHTML);
        if(e[i].id.indexOf('row_selling')==0) sub_total_sell += float(e[i].innerHTML);
	}
	//sub total selling and price
	$('td_sub_total_selling').innerHTML = round(sub_total_sell,2);
 	$('total_selling').value=round(sub_total_sell,2);
 	// sub total amt
	$('td_sub_total_amount').innerHTML = round(total_amount,2);
	if($('td_sub_total_foreign_amount') != undefined) $('td_sub_total_foreign_amount').innerHTML = round(total_foreign_amount,2);
	$('sub_total_amt').value = round(total_amount,2);
	if($('sub_total_foreign_amt') != undefined) $('sub_total_foreign_amt').value = round(total_foreign_amount,2);
	
	//if(discount_percent>0){
	//    $('tr_discount_amount').show();
	//    discount_amount = round(float(total_amount*(discount_percent*0.01)),2);
    //    total_amount = total_amount - discount_amount;
	//}else{
    //    $('tr_discount_amount').hide();
	//}
	var total_amt = total_amount;
	if(discount){
        if(disc1){  // sheet discount 1
		    discount_amt = float(round(total_amt*(disc1/100), 2));
		    if(total_foreign_amount) foreign_discount_amt = float(round(total_foreign_amount*(disc1/100), 2));
		    total_discount_amt += discount_amt;
			total_foreign_discount_amt += foreign_discount_amt;
	        total_amt -= discount_amt;
			total_foreign_amount -= foreign_discount_amt;
		}
		if(disc2){  // further discount
		    discount_amt = float(round(total_amt*(disc2/100), 2));
			if(total_foreign_amount) foreign_discount_amt = float(round(total_foreign_amount*(disc1/100), 2));
		    total_discount_amt += discount_amt;
		    total_foreign_discount_amt += foreign_discount_amt;
	        total_amt -= discount_amt;
	        total_foreign_amount -= foreign_discount_amt;
		}
		$('tr_discount_amount').show();
	}else $('tr_discount_amount').hide();

	
	total_discount_amt = float(total_discount_amt);
	total_foreign_discount_amt = float(total_foreign_discount_amt);
    // total amount
	$('display_total_amount').innerHTML=round(total_amt,2);
	if($('display_total_foreign_amount') != undefined) $('display_total_foreign_amount').innerHTML=round(total_foreign_amount,2);
	$('total_amount').value=round(total_amt,2);
	if($('total_foreign_amount') != undefined) $('total_foreign_amount').value=round(total_foreign_amount,2);
	// discount amount
	$('input_discount_amount').value = round(total_discount_amt, 2);
	if($('input_foreign_discount_amount') != undefined) $('input_foreign_discount_amount').value = round(total_foreign_discount_amt, 2);
	$('td_display_discount_amount').update(round(total_discount_amt*-1, 2));
	if($('td_display_foreign_discount_amount') != undefined) $('td_display_foreign_discount_amount').update(round(total_foreign_discount_amt*-1, 2));
	
	if(approval_screen==1){
        //$('input_approval_total_and_discount_info').value = total_amount+","+discount_percent+","+discount_amount;
        $('input_approval_total_and_discount_info').value = total_amt+","+discount+","+total_discount_amt;
	}
}

function calc_all_items(){
	
	var row_ctn=0, total_ctn=0;
	var row_pcs=0, total_pcs=0;
	var total_amount=0;
	var total_qty=0;
	
	var item_fraction=new Array();
	var item_cost=new Array();
	var item_qty=new Array();
	var item_selling = new Array();
	
	var row_ctn=new Array();
	var row_pcs=new Array();
	
	var row_selling = 0;
	var total_selling = 0;
	
	if ($('ci_items')==undefined) return;
	
	var e = $('ci_items').getElementsByClassName('uom');
	for(var i=0;i<e.length;i++)	{
		var temp_2 =new RegExp('^cost_price_');
		if (temp_2.test(e[i].id)){
			var line =e[i].title.split(",");
			item_cost[line[1]]=float(e[i].value);
		}
	
 		var temp_3 =new RegExp('^qty_ctn');
		if (temp_3.test(e[i].id)){
			var line =e[i].title.split(",");
			if(!row_ctn[line[1]]){
				row_ctn[line[1]]=0;
			}
			row_ctn[line[1]]=float(e[i].value);
			total_ctn+=float(e[i].value);
		}
		
 		var temp_4 =new RegExp('^qty_pcs');
		if (temp_4.test(e[i].id)){
			var line =e[i].title.split(",");
			if(!row_pcs[line[1]]){
				row_pcs[line[1]]=0;
			}
			row_pcs[line[1]]=float(e[i].value);
			total_pcs+=float(e[i].value);
		}

		var temp_5 =new RegExp('^uom_fraction');
		if (temp_5.test(e[i].id)) {
			item_fraction[e[i].title]=float(e[i].value);
		}
		
  		var temp_6 =new RegExp('^row_qty');
		if (temp_6.test(e[i].id)) {
			var line =e[i].title.split(",");
			item_qty[line[1]]=float(e[i].innerHTML);
		}
		
		var temp_s =new RegExp('^selling_price_');
		if (temp_s.test(e[i].id)){
			var line =e[i].title.split(",");
			item_selling[line[1]]=float(e[i].value);
		}
				
 		var temp_7 =new RegExp('^row_amount');
		if (temp_7.test(e[i].id)){
			var line =e[i].title.split(",");
			item_id=line[1];
			row_total=round(item_cost[item_id]*item_qty[item_id]/item_fraction[item_id],2);
			
			// calculate row discount if it is lost invoice
			//if(show_per){
				//var discount = float($('row_discount,'+item_id).innerHTML);
				//var discount_per = float(discount*0.01);
				//var discount_amount = row_total*discount_per;
				//row_total = round(row_total-discount_amount,2);
				
				var discount = $('input_discount_per,'+item_id).value;
				var disc1 = float(discount.split("+")[0]);
				var disc2 = 0;
				if(discount.split("+").length>1)	disc2 = float(discount.split("+")[1]);

			    if(disc1){  // sheet discount 1
				    discount_amt = row_total*(disc1/100);
			        row_total -= discount_amt;
				}
				if(disc2){  // further discount
				    discount_amt = row_total*(disc2/100);
			        row_total -= discount_amt;
				}
				row_total = round(row_total,2);
			//}
			
			$('row_amount'+item_id).innerHTML=row_total;
			total_amount+=float(row_total);
		}
		
		var temp_8 =new RegExp('^row_selling');
		if (temp_8.test(e[i].id)){
			var line =e[i].title.split(",");
			item_id=line[1];
			row_selling = round(item_selling[item_id]*item_qty[item_id]/item_fraction[item_id],2);

			$('row_selling'+item_id).innerHTML = row_selling;
			total_selling += float(row_selling);
		}
	}
	
	$('t_ctn').innerHTML=round(total_ctn);
	$('t_pcs').innerHTML=round(total_pcs);
	$('total_ctn').value=round(total_ctn);
	$('total_pcs').value=round(total_pcs);
	$('display_total_amount').innerHTML=round(total_amount,2);
	$('total_amount').value=round(total_amount,3);
	$('td_sub_total_selling').innerHTML = total_selling;
	
	recal_total();
}

*/

CI_MODULE = {
	f: undefined,
	initilize: function(){
		this.f = document.f_a;
	},
	// function when user toggle price is inclusive tax
	display_cost_price_is_inclusive_changed: function(item_id){
		this.item_row_changed(item_id);
	},
	// function when user change display cost price
	display_cost_price_changed: function(item_id){
		this.item_row_changed(item_id);
	},
	// function when user change cost price
	cost_price_changed: function(item_id, need_round){
		if(need_round){
			mf(this.f['cost_price['+item_id+']'], 2);
		}
		this.item_row_changed(item_id);
	},
	// function to calculate real cost price from display cost price
	calculate_real_cost_price: function(item_id){
		//console.log('calculate_real_cost_price');
		// get the display cost price
		var inp_display_cost_price = this.f['display_cost_price['+item_id+']'];
		// round price to 3
		mf(inp_display_cost_price, 3);
		
		var display_cost_price = float(round(inp_display_cost_price.value,3));
		
		// not allow negative
		if(display_cost_price<0){
			display_cost_price = 0;
			inp_display_cost_price.value = 0;
		}
		var cost_price = display_cost_price;
		
		// check display cost price inclusive
		if(this.f['display_cost_price_is_inclusive['+item_id+']'].checked){
			// is inclusive tax
			// calculate before tax price
			var gst_rate = float(this.f["gst_rate["+item_id+"]"].value);
			if(gst_rate>0){
				cost_price = display_cost_price / (100+gst_rate) * 100;
			}
			$('div_cost_price_info-'+item_id).show();
		}else{
			// exclusive tax
			$('div_cost_price_info-'+item_id).hide();
		}
		
		// display cost price to label
		this.f['cost_price['+item_id+']'].value = cost_price;
		$('span_cost_price_label-'+item_id).update(round(cost_price,4));
	},
	// item row changed
	item_row_changed: function(item_id){
		//console.log('item_row_changed');
		// calculate real cost price
		if(is_under_gst){
			this.calculate_real_cost_price(item_id);
		}
		
		// recalculate row total
		this.item_row_recal(item_id);
	},
	// function to recal item row
	item_row_recal: function(item_id){
		row_recalc(this.f['cost_price['+item_id+']']);
	},
	// function when user change row gst
	item_gst_changed: function(item_id){
		// update the selected gst
		update_selected_gst(item_id);
			
		// recalculate row
		this.item_row_changed(item_id);
	},
	// function when user change item uom
	item_uom_changed: function(item_id){
		var sel = $('sel_uom'+item_id);
		var a = sel.value.split(",");
		var old_fraction = float($('uom_fraction'+item_id).value);
		var old_cost;
		var new_cost;
				
		// check old fraction
		if(is_under_gst){
			old_cost=float(this.f['display_cost_price['+item_id+']'].value)/old_fraction;
			new_cost=old_cost*float(a[1]);
			
			// change new cost
			this.f['display_cost_price['+item_id+']'].value = round(new_cost, 3);
		}else{
			
			old_cost=float(this.f['cost_price['+item_id+']'].value)/old_fraction;
			new_cost=old_cost*float(a[1]);
			
			// change new cost
			this.f['cost_price['+item_id+']'].value = round(new_cost, 3);
		}
		
		
		// foreign currency
		if(consignment_modules && consignment_multiple_currency){
			var old_foreign_cost=float($('foreign_cost_price_'+item_id).value)/old_fraction;
			var new_foreign_cost=old_foreign_cost*float(a[1]);
			$('foreign_cost_price_'+item_id).value=round(new_foreign_cost,3);
		}
		
		// update new uom
		$('uom_id'+item_id).value=a[0];
		$('uom_fraction'+item_id).value=a[1];
		
		// change ctn/pcs
		this.check_row_ctn_pcs_input(item_id);
		
		// recalulate row
		this.item_row_changed(item_id);

		// calc foreign
		//if(consignment_modules && consignment_multiple_currency && do_type =='transfer') foreign_variable_recalc();
	},
	// function to check row ctn/pcs input
	check_row_ctn_pcs_input: function(item_id){
		var inp_qty_ctn_list = $$('#titem'+item_id+' input.inp_qty_ctn');
		var uom_fraction = float($('uom_fraction'+item_id).value);
		
		for(var i=0,len=inp_qty_ctn_list.length; i<len; i++){
			var inp = inp_qty_ctn_list[i];
			if(uom_fraction == 1){
				inp.value = '--';
				inp.disabled = true;
			}else{
				inp.disabled = false;
				if(inp.value == '--' || inp.value == '-'){
					inp.value = '';
				}
			}
		}
	},
	// function when user change foreign cost price
	foreign_cost_price_changed: function(item_id){
		var exchange_rate = (document.f_a['exchange_rate'].value<=0)? 1 : document.f_a['exchange_rate'].value;
		var inp_foreign = document.f_a['foreign_cost_price['+item_id+']'];
		var inp_display_cost_price = document.f_a['display_cost_price['+item_id+']'];
		
		mf(inp_foreign, 3);
		if(inp_foreign.value == 0) inp_foreign.value = inp_cost_price.value;
		else{
			if(is_under_gst){
				inp_display_cost_price.value = round(inp_foreign.value*exchange_rate, 3);
			}else{
				this.f['cost_price['+item_id+']'].value = round(inp_foreign.value*exchange_rate, 3);
			}
		}
		this.cost_price_changed(item_id);
	},
	// function when exchange rate changed
	exchange_rate_changed: function(){
		var rate = float(document.f_a['exchange_rate'].value);
		if(rate<=0){
			document.f_a['exchange_rate'].value = 1;
		}
		// get all items row
		var tr_ci_item_row_list = this.get_all_items_row();
		// loop them
		for(var i=0,len=tr_ci_item_row_list.length; i<len; i++){
			// get the row item id
			var item_id = this.get_item_id_by_ele(tr_ci_item_row_list[i]);
			// recalculate foreign cost
			this.foreign_cost_price_changed(item_id);
		}
	},
	// function to get all items row
	get_all_items_row: function(){
		return $$('#ci_items tr.tr_ci_item_row');
	},
	// function to get item row id
	get_item_id_by_ele: function(ele){
		var parent_ele = ele

		while(parent_ele){    // loop parebt until it found the ele
		    if(parent_ele.tagName.toLowerCase()=='tr'){
                if($(parent_ele).hasClassName('tr_ci_item_row')){    // found the row
					break;  // break the loop
				}
			}
			// still not found, continue to get from parent node
            parent_ele = parent_ele.parentNode;
		}

		if(!parent_ele) return 0;

		var item_id = $(parent_ele).readAttribute('item_id');
		return item_id;
	}
}

function submit_multi(){
	// selected count
	var item_count = 0;
	$$('#tbl_multi_add input.mul').each(function(chx){
		if(chx.checked)	item_count++;
	});
	if(item_count<=0){
		alert('Nothing to add');
		return;
	}
	
	var btn_submit_multi = $('btn_submit_multi');
	btn_submit_multi.disabled = true;
	btn_submit_multi.value = 'Processing...';
	
	parms = Form.serialize(document.f_a)+'&a=save_multi_add&'+Form.serialize(document.f_mul);
	
	if(consignment_modules && masterfile_branch_region && consignment_multiple_currency) parms += "&currency_code="+branch_currency_code[document.f_a['ci_branch_id'].value];
	
    ajax_request(phpself,{
        method: 'post',
		parameters: parms,
		onComplete: function(e){
			new Insertion.Bottom($('ci_items'), e.responseText);
			var spans_no = $$('#new_sheets span.no');
			
			for(var i=0; i<spans_no.length; i++){
                spans_no[i].id = 'no_'+(i+1);
                spans_no[i].update(' '+(i+1)+'.');
			}
			
			default_curtain_clicked();
		}
	});
}
</script>
{/literal}

<form name="f_do_reset" method="post" style="display:none;">
<input type=hidden name="a" value="do_reset">
<input type=hidden name="branch_id" value="{$form.branch_id}">
<input type=hidden name="id" value="{$form.id}" >
<input type=hidden name=reason value="">
<input type=hidden name=curr_date value="{$form.ci_date}">
</form>

<div id="div_multi_add" style="display:none;border:1px solid black;position:absolute;height:500px;width:600px;background:white;padding:3px;z-index:10000;">
	<div id="div_multi_add_content" style="overflow-x:hidden;overflow-y:auto;height:450px;">
	
	</div>
	<p align="center"><input type="button" value="Add" onClick="submit_multi(this);" id="btn_submit_multi" /></p>
</div>

<div id=wait_popup style="display:none;position:absolute;z-index:10000;background:#fff;border:1px solid #000;padding:5px;width:200;height:100">
	<p align=center>
		Please wait..<br /><br /><img src="ui/clock.gif" border="0" />
	</p>
</div>

<div style="position: absolute; z-index: 20000; border: 2px solid rgb(206, 0, 0); background-color: rgb(255, 255, 255); background-image: url(&quot;/ui/ndiv.jpg&quot;); background-repeat: repeat-x; padding: 0pt ! important; top: 208px; left: 540px; display:none;" class="curtain_popup" id="div_process_gst_price">
	<div style="border: 2px ridge rgb(206, 0, 0); color: white; background-color: rgb(206, 0, 0); padding: 2px; cursor: default;" id="div_process_gst_price_header"><span>Price Calculation</span>
		<span style="float: right;">
			<img align="absmiddle" class="clickable" onclick="default_curtain_clicked();" src="/ui/closewin.png">
		</span>
	</div>
	<br />
	<table cellspacing="0" border="0" padding="0">
		<tr>
			<td>Price Included GST:</td>
			<td><input type="text" size="8" id="pgp_gst_price" class="r" onkeyup="process_gst_price(this);" onkeypress="price_onkeypress(event);"></td>
		</tr>
		<tr>
			<td>GST (<span id="span_pgp_gst_rate"></span>%)</td>
			<td><input type="text" size="8" id="pgp_gst" class="r" readonly></td>
		</tr>
		<tr>
			<td>Price Excluded GST:</td>
			<td><input type="text" size="8" id="pgp_price" class="r" readonly></td>
		</tr>
	</table>
	<p align="center">
		<input type="hidden" id="pgp_item_id" value="" />
		<input type=button value="Confirm" onclick="process_gst_price_clicked()">
		<input type=button value="Back" onclick="default_curtain_clicked()">
	</p>
</div>

{if $form.approval_screen}
<form name="f_b" method=post>
<input type=hidden name=ci_no value={$form.ci_no}>
<input type=hidden name=branch_id value={$form.branch_id}>
<input type=hidden name=ci_branch_id value={$form.ci_branch_id}>
<input type=hidden name=id value="{$form.id}">
<input type=hidden name=comment value="">
<input type=hidden name=a value="approve">
<input type=hidden name=approvals value={$form.approvals}>
<input type=hidden name=approval_history_id value={$form.approval_history_id}>
<input type=hidden name="default_discount_percent" id="input_approval_default_discount_percent" value="{$form.discount_percent|number_format:2}" />
<input type=hidden name="total_and_discount_info" id="input_approval_total_and_discount_info" value="{$form.total_amount},{$form.discount_percent|number_format:2},{$form.discount_amount|number_format:2}" />
<input type=hidden name=curr_date value="{$form.ci_date}">
{if $approval_on_behalf}
<input type="hidden" name="on_behalf_of" value="{$approval_on_behalf.on_behalf_of}" />
<input type="hidden" name="on_behalf_by" value="{$approval_on_behalf.on_behalf_by}" />
{/if}
</form>
{/if}

{if !$form.approved}
<h1>Consignment {if $page_type eq 'lost'}Lost{elseif $page_type eq 'over'}Over{/if} Invoice {if $form.id<$time_value}(ID#{$form.id}){else}(New){/if}
</h1>
{else}
<h1>Consignment {if $page_type eq 'lost'}Lost{elseif $page_type eq 'over'}Over{/if} Invoice {if $form.ci_no}(CI/{$form.ci_no}){else}{if $form.id<$time_value}(ID#{$form.id}){/if}{/if}
</h1>
{/if}
<h3>Status:

{if $form.approved}
	Fully Approved
{elseif $form.status == 4}
	Cancelled/Terminated
{elseif $form.status == 2}
	Rejected
{elseif $form.status == 1}
	In Approval Cycle
{elseif $form.status == 0}
    Saved Invoice
{/if}
</h3>
{include file=approval_history.tpl}
<form name="f_a" method=post ENCTYPE="multipart/form-data">
<input type=hidden name=a value="save">
<input type=hidden name=branch_id value="{$form.branch_id|default:$sessioninfo.branch_id}" />
<input type=hidden name=id value="{$form.id}">
<input type=hidden name=reason value="">
<input type=hidden name=ci_no value={$form.ci_no}>
<input type=hidden name=approval_history_id value={$form.approval_history_id}>
<input type="hidden" name="type" value="{$page_type}">
<input type="hidden" name="is_under_gst" value="{$form.is_under_gst}">

<div class="stdframe" style="background:#fff">
<h4>General Informations</h4>

{if $errm.top}
<div id=err><div class=errmsg><ul>
{foreach from=$errm.top item=e}
<li> {$e}
{/foreach}
</ul></div></div>
{/if}

<div id=errpr></div>

<table border=0 cellspacing=0 cellpadding=4>
<tr>
	<th width=150 align=left nowrap>Invoice Date</th>
	<td colspan=5>
	{if $form.ci_date}
	    {assign var=ci_date value=$form.ci_date}
	{else}
	    {assign var=ci_date value=$smarty.session.ci_date|default:$smarty.now}
	{/if}
	<input name="ci_date" id="added1" size=12 onchange="on_date_changed();" value="{$ci_date|date_format:"%Y-%m-%d"}" >
	{*if $form.status<1 || $form.status eq '2'*}
	{if !$readonly && !$form.approval_screen}
	<img align=absmiddle src="ui/calendar.gif" id="t_added1" style="cursor: pointer;" title="Select Date">
	{/if}
	</td>
</tr>

{if $form.id<$time_value}
<tr>
	<td width=120 align=left><b>Owner</b></td>
	<td colspan=5 style="color:blue;">
	{$form.user}
	</td>
</tr>
{/if}

<tr>
	<td><b>Discount (%)</b></td>
	<td width=120><input type="text" name="discount_percent" id="input_discount_percent" value="{$form.discount_percent|ifzero:''}" size="10" onChange="change_discount(this);" onblur="change_discount(this);" style="text-align:right;" /> %
	</td>
	{if $config.consignment_invoice_discount_selling_price_percent}
	<td width="150"><b>Discount Selling Price (%)</b></td>
	<td {if !$config.consignment_invoice_discount_item_row_percent }colspan="3"{/if}>
		<input type="text" name="discount_selling_price_percent" id="input_discount_selling_price_percent" value="{$form.discount_selling_price_percent|ifzero:''}" size="10" onblur="change_discount(this);" style="text-align:right;" /> %</td>
	{/if}
	{if $config.consignment_invoice_discount_item_row_percent }
	<td width="150"><b>Bearing Percent<!--Discount Item Row-->(%)</b></td>
	<td width=120><input type="text" name="discount_item_row_percent" id="input_discount_item_row_percent" value="{$form.discount_item_row_percent|ifzero:''}" size="10" onblur="change_discount(this);" style="text-align:right;" /> %</td>
	{/if}
</tr>

{if $config.consignment_modules && $config.masterfile_branch_region && $config.consignment_multiple_currency}
<tr>
	<td><b>Exchange Rate</b></td>
	<td colspan=5>
		<input type="text" name="exchange_rate" size="15" value="{if $form.exchange_rate ne 1}{$form.exchange_rate}{/if}" onchange="CI_MODULE.exchange_rate_changed();" 
		 class="r">
	</td>
</tr>
{/if}

<tr>
	<td valign=top width=120><b>Remarks</b></td>
	<td colspan=5>
	<textarea rows="2" cols="68" name=remark onchange="uc(this);">{$form.remark}</textarea>
	</td>
</tr>

<tr>
	<td valign=top width=120><b>Invoice To</b></td>
	<td colspan=5>
	<input type="hidden" name="delivery_type" value="1" />
	{*<input type=radio name="delivery_type" value=1 {if $form.ci_branch_id || $form.id>$time_value}checked{/if} onChange="select_type(this.value);">
	*}Branches &nbsp;&nbsp;
	<select name="ci_branch_id" id=delivery_branches {if !$form.ci_branch_id && $form.id<$time_value}style="display:none;" disabled="true"{/if} onChange="change_lost_inv_branch();" {if $form.mr_branch_id && $form.mr_year && $form.mr_month}onfocus="this.blur(); alert('Cannot change this option because this document is generated by Monthly Report.');" readonly{/if}>
	{foreach from=$branches key=bid item=b}
	    {if !$branch_group.have_group.$bid}
	    	<option value="{$bid}" {if $bid eq $form.ci_branch_id}selected {/if}>{$b.code} - {$b.description}</option>
	    {/if}
	{/foreach}
	{foreach from=$branch_group.header key=bgid item=bg}
	    <optgroup label="{$bg.code}">
	        {foreach from=$branch_group.items.$bgid key=bid item=b}
	            <option value="{$bid}" {if $form.ci_branch_id eq $bid}selected {/if}>{$b.code} - {$b.description}</option>
	        {/foreach}
	    </optgroup>
	{/foreach}
	</select> <span id="span_branch_changed"></span>
	<br>
	{*<input type=radio name="delivery_type" value=2 {if $form.open_info.name}checked{/if} onChange="select_type(this.value);">Open*}
	</td>
</tr>	


<tr id=delivery_open {if !$form.open_info.name}style="display:none;"{/if}>	
	<td valign=top width=120>&nbsp;</td>
	<td colspan=5>
		<table>
			<tr>
				<td width=100>Company Name</td>
				<td><input id=oi_name name="open_info[name]" value="{$form.open_info.name}" size=51 onchange="uc(this);"></td>
			</tr>
			<tr>
				<td valign=top width=100>Address </td>
				<td><textarea id=oi_address name=open_info[address] rows=5 cols=38  onchange="uc(this);">{$form.open_info.address}</textarea></td>
			</tr>
		</table>
	</td>
</tr>
<tr>
	<td valign="top"><b>Settings</b></td>
	<td colspan=5 style="background-color: #F3F3F0; border: 1px solid #CCCCCC;padding: 5px;">
		<input type="checkbox" name="show_per" {if $form.show_per}checked {/if} value="1" onChange="show_per_changed();" /> Use item branch trade discount
		<span id="span_show_per_loading"></span><br />
		<input type="checkbox" name="auto_split_by_price_type" align="absmiddle" {if $form.auto_split_by_price_type}checked {/if} value="1" /> Auto Split by Price Type when confirm.<br />
		<input type="checkbox" name="bring_item_disc_to_sheet_disc" align="absmiddle" {if $form.id<$time_value}{if $form.bring_item_disc_to_sheet_disc}checked {/if}{else}{if $config.ci_bring_item_disc_to_sheet_disc_default_on}checked {/if}{/if} value="1" /> Auto bring item discount to sheet discount when confirm. (Only if there is no split and all items have same discount percent).<br />
		{if $form.is_under_gst && $gst_export_settings}
			{*<input type="checkbox" name="is_export" align="absmiddle" {if $form.is_export}checked{/if} onclick="on_export_clicked(this);" value="1" /> Export to foreign customer. (all GST code selections will be disabled and default as {$gst_export_settings.code} [{$gst_export_settings.rate}%])<br />*}
		{/if}
	</td>
</tr>
</table>

<div id=srefresh style="display:none; padding-top:10px; padding-left:130px; ">
<input id=refresh_btn type=button onclick="void(refresh_tables())" style="font-size:1.5em; color:#fff; background:#091" value="click here to continue">
</div>
</td>
</tr>
</table>
</div>

<br>

{if $errm_link_code}
<div id=err>
<div class=errmsg>
<ul>
<li>
The following Link Code are INVALID :
</ul>
</div>
{foreach from=$errm_link_code item=e}
<b>{$e}</b><br>
{/foreach}
</div>
{/if}

<br>

{if $errm_sku_item_code}
<div id=err>
<div class=errmsg>
<ul>
<li>The following ARMS Code are INVALID :
</ul>
</div>
{foreach from=$errm_sku_item_code item=e}
<b>{$e}</b><br>
{/foreach}
</div>
{/if}

<br>

<div id="new_sheets">
{include file=consignment_invoice.new.sheet.tpl}
{if (!$form.status || $form.status=='2') && $form.create_type ne '3' && !$form.approval_screen && !$form.approved && !$readonly}	
	<table id=tbl_sku width=100% style="border:1px solid #999; padding:2px; background-color:#dddddd">
	{if $config.ci_accept_grn_barcode}
	<tr>
	<td><b>Scan Barcode : </b> <input id=grn_barcode onkeypress="if (event.keyCode==13) add_grn_barcode_item(this.value)"> <input type=button value="Add" onclick="add_grn_barcode_item($('grn_barcode').value)" style="background:#ece;border:1px solid #fff;border-right:1px solid #333; border-bottom:1px solid #333;"></td>
	</tr> 
	<tr><td colspan=2><hr noshade size=1></td></tr>
	{/if}
	<tr class=normal>
	<td nowrap>
	<input name="sku_item_id" size=3 type=hidden>
	<input name="sku_item_code" size=13 type=hidden>
	
	<b>Search : </b><input id="autocomplete_sku" name="sku" size=35 onclick="this.select()">
	
	<input type=button value="Add" onclick="add_item()" style="background:#ece;border:1px solid #fff;border-right:1px solid #333; border-bottom:1px solid #333;">
	<input type=button value="Multiple Add" onclick="open_multi_add()" style="background:#ece;border:1px solid #fff;border-right:1px solid #333; border-bottom:1px solid #333;">
	
	<div id="autocomplete_sku_choices" class="autocomplete" style="display:none;height:150px !important;width:500px !important;overflow:auto !important;z-index:100"></div>
	<br>
	<img src=ui/pixel.gif width=40 height=1>
	<input onchange="reset_sku_autocomplete()" type=radio name="search_type" value=1> MCode &amp; {$config.link_code_name}
	<input onchange="reset_sku_autocomplete()" type=radio name="search_type" value=2 checked /> Article No
	<input onchange="reset_sku_autocomplete()" type=radio name="search_type" value=3> ARMS Code
	<input onchange="reset_sku_autocomplete()" type=radio name="search_type" value=4> Description
	</td>
	</tr>
	</table>
	<script>reset_sku_autocomplete();</script>
{/if}
</div>

</form>


<p id=submitbtn align=center>

{if $form.is_approval and $form.status==1 and $form.approved==0 and $form.approval_screen}
<input type=button value="Approve" style="background-color:#f90; color:#fff;" onclick="ci_approve()">
<input type=button value="Reject" style="background-color:#f90; color:#fff;" onclick="ci_reject()">
<input type=button value="Terminate" style="background-color:#900; color:#fff;" onclick="ci_cancel()">
{/if}

{if !$form.approval_screen}
	{if !$readonly}
		{if (!$form.status || $form.status==2)}
		<input name=bsubmit type=button value="Save & Close" style="font:bold 20px Arial; background-color:#f90; color:#fff;" onclick="ci_save()" >
		{/if}
		
		{if $form.id<$time_value}
		<input type=button value="Delete" style="font:bold 20px Arial; background-color:#900; color:#fff;" onclick="ci_delete()">
		{else}
		<input type=button value="Close" style="font:bold 20px Arial; background-color:#09c; color:#fff;" onclick="document.location='{$smarty.server.PHP_SELF}'">
		{/if}
		
		{if (!$form.status || $form.status==2)}
		<input type=button value="Confirm" style="font:bold 20px Arial; background-color:#091; color:#fff;" onclick="ci_confirm()">
		{/if}
	{else}
	    {if $form.approved and ($sessioninfo.level>=$config.doc_reset_level)}
	        <input type=button value="Reset" style="font:bold 20px Arial; background-color:#900; color:#fff;" onclick="do_reset();">
	    {/if}
		<input type=button value="Close" style="font:bold 20px Arial; background-color:#09c; color:#fff;" onclick="document.location='{$smarty.server.PHP_SELF}'">
	{/if}
{/if}

</p>

{if !$form.approval_screen}
	{include file=footer.tpl}
{/if}

<script>
CI_MODULE.initilize();

{if $config.consignment_modules && $config.masterfile_branch_region && $config.consignment_multiple_currency}
	foreign_variable_handler();
	//change_lost_inv_branch();
{/if}

{if $readonly || $form.approval_screen}
	Form.disable(document.f_a);
	{if $form.discount_percent>0}$('tr_discount_amount').show();{/if}
	{if $form.approval_screen}
	    $('input_discount_percent').disabled = false;
		if($('input_discount_selling_price_percent')) $('input_discount_selling_price_percent').disabled = false;
		if($('input_discount_item_row_percent')) $('input_discount_item_row_percent').disabled = false;
	{/if}	
{else}
	//refresh the session each 25 minutes to avoid timeout when user take long time (>30 mins) to select sku.
	{literal}
	new Ajax.PeriodicalUpdater('', "dummy.php", {frequency:1500});
	new Draggable('div_process_gst_price',{ handle: 'div_process_gst_price_header'});
	{/literal}
	init_calendar();	
{/if}
calc_all_items();
prev_price_indicate = $('pi_{$form.price_indicate|default:1}');

</script>
