{*
6/3/2010 3:44:48 PM Andy
- Fix some wording mistake.

7/21/2010 11:31:38 AM Andy
- Fix CN/DN "Auto split by price type" checkbox after saved, next time open it will not retrain to previous saved status.

11/9/2010 11:22:25 AM Andy
- Change if item have no discount, show zero instead of empty %.

11/3/2011 4:55:43 PM Justin
- Added replace feature for cost, cost price, selling price and trade discount code when branch changed base on config cm_use_deliver_branch_sp.

12/15/2011 3:01:43 PM Justin
- Added Exchange Rate field.
  * Required config "consignment_multiple_currency".
  * load from Consignment Forex.
  * All exchange is place on array in JS and replace current one whenever user select different branches.
  * Added an ability to show/hide foreign price/amount fields base on branch currency code as if it is not roreign currency code.
- Added new function to monitor and maintain all foreign cost/amount base on the price indicate and exchange rate change by user.

1/10/2012 5:15:32 PM Justin
- Fixed bugs that loads data incomplete when change deliver branch.

11/23/2012 2:17:00 PM Fithri
- after monthly report has been printed, user cannot do further edit (reject, approval or submit) on that month - for consignment only

1/25/2013 4:46 PM Justin
- Enhanced to disable Deliver To dropdown list when found it is generated by Monthly Report.

8/1/2013 2:37 PM Fithri
- bugfix : add checking for items in temp table before save/confirm in case the document is open in more than one tab/window

12/23/2013 10:23 AM Fithri
- new module 'Stucked Documents Approval'

3/24/2014 5:27 PM Justin
- Modified the wording from "Finalize" to "Finalise".

1/21/2015 10:46 AM Justin
- Enhanced to have GST calculation.

3/9/2015 5:03 PM Justin
- Bug fixed on discount calculation errors.

3/10/2015 3:21 PM Justin
- Bug fixed on javascript unable to find exchange rate field.

3/17/2015 3:48 PM Andy
- Fix price change to zero bug.

3/18/2015 3:31 PM Justin
- Bug fixed on discount calculation errors.

3/26/2015 10:15 AM Justin
- Bug fixed on cost price will become null when switching between delivery branches that with/without region.

3/26/2015 3:18 PM Justin
- Enhanced to have new feature that calculate from GST price into net price.

4/1/2015 5:50 PM Andy
- Temporary remove the feature is_export checkbox.

6/9/2015 1:56 PM Andy
- Enhanced to have display cost price feature for CN/DN.
- Enhanced CN/DN recalculation.

6/9/2015 5:22 PM Andy
- Fix js error if no foreign.

6/19/2015 3:41 PM Andy
- Fix cost price rounding issue when no GST.

12/4/2015 9:21AM DingRen
- add check login for form submit and ajax call
*}

{if !$form.approval_screen}
	{include file='header.tpl'}
{else}
	<hr noshade size=2>
{/if}
<link rel="stylesheet" type="text/css" media="all" href="js/jscalendar/calendar-blue.css" title="calendar-blue" />

<script type="text/javascript" src="js/jscalendar/calendar.js"></script>
<script type="text/javascript" src="js/jscalendar/lang/calendar-en.js"></script>
<script type="text/javascript" src="js/jscalendar/calendar-setup.js"></script>

<style>

{literal}
.non_editable{
	background:#ddd;
}
.input_no_border input, .input_no_border select{
	border:1px solid #999;
	background: #fff;
	font-size: 10px;
	padding:2px;
}
input[disabled],input[readonly],select[disabled], textarea[disabled]{
  color:black;
  background: #ddd;
}
{/literal}
</style>

<script>
var phpself = '{$smarty.server.PHP_SELF}';
var cm_use_deliver_branch_sp = '{$config.cm_use_deliver_branch_sp}';
var consignment_modules = '{$config.consignment_modules}';
var masterfile_branch_region = '{$config.masterfile_branch_region}';
var consignment_multiple_currency = '{$config.consignment_multiple_currency}';

// gst
var enable_gst = int('{$config.enable_gst}');
var global_gst_start_date = '{$config.global_gst_start_date}';
var is_under_gst = int('{$form.is_under_gst}');
var branch_gst_register_no = '{$sessioninfo.gst_register_no}';
var branch_gst_start_date = '{$sessioninfo.gst_start_date}';
var gst_is_active = int('{$sessioninfo.gst_is_active}');
var skip_gst_validate = int('{$sessioninfo.skip_gst_validate}');
var gst_export = '{$gst_export_settings.id}';

var branch_currency_code = [];
var branch_exchange_rate = [];
{if $config.consignment_modules && $config.masterfile_branch_region && $config.consignment_multiple_currency}
	{foreach from=$branches item=b}
		{if $form.to_branch_id eq $b.id}
			{assign var=exchange_rate value=$form.exchange_rate}
		{else}
			{assign var=exchange_rate value=$b.exchange_rate}
		{/if}
		branch_currency_code['{$b.id}'] = "{$b.currency_code|escape:javascript}";
		branch_exchange_rate['{$b.id}'] = "{$exchange_rate|escape:javascript}";
	{/foreach}
{/if}

{literal}
function init_calendar(){
	Calendar.setup({
		inputField     :    "added1",
		ifFormat       :    "%Y-%m-%d",
		button         :    "t_added1",
		align          :    "Bl",
		singleClick    :    true
	});
}

function active_btn(ele){
	var to_branch_id = 0;
	if(document.f_a['to_branch_id'])	to_branch_id = document.f_a['to_branch_id'].value;
	
	if(document.f_a['exchange_rate'] != undefined){
		if(!consignment_multiple_currency || !to_branch_id || branch_currency_code[to_branch_id] == "" || branch_currency_code[to_branch_id] == "RM" ){
			document.f_a['exchange_rate'].readOnly = true;
			document.f_a['exchange_rate'].disabled = true
			document.f_a.elements['exchange_rate'].value = '';
		}else{
			document.f_a['exchange_rate'].readOnly = false;
			document.f_a['exchange_rate'].disabled = false;
			
			// check currency exchange rate
			if(masterfile_branch_region){
				if(to_branch_id>0){
					document.f_a.elements['exchange_rate'].value = branch_exchange_rate[to_branch_id];
				}else{
					document.f_a.elements['exchange_rate'].value = 0;
				}
			}
		}
	}
					
	if($('div_sheets').style.display==''){
	    if(ele.value<=0)    return false;
        var tr_item = $$('#div_sheets tr.tr_item');
		if(tr_item.length>0){
			$('span_invoice_to_change_loading').update(_loading_);
			new Ajax.Request(phpself,{
				parameters: $(document.f_a).serialize()+'&a=ajax_change_cn_branch',
				onComplete: function(e){
                    eval("var json = "+e.responseText);
					
					var sheet_discount = '';
					if(json['sheet_discount'])  var sheet_discount = json['sheet_discount'];
					document.f_a['discount'].value = sheet_discount;
					discount_changed();
					
					for(var i=0; i<tr_item.length; i++){
					    var item_id = tr_item[i].id.split(",")[1];
						var discount = '0';
						if(json[item_id]['discount_per'])   discount = json[item_id]['discount_per'];
						var sb2 = 0;
						if(json[item_id]['sb2']) sb2 = json[item_id]['sb2'];
						if(cm_use_deliver_branch_sp){ // use deliver branch selling price
							if(json[item_id]['cost']) $('cost,'+item_id).value = round(json[item_id]['cost'], 3);
							if(json[item_id]['cost_price']) $('cost_price,'+item_id).value = round(json[item_id]['cost_price'], 3);
							if(json[item_id]['selling_price']) $('selling_price,'+item_id).value = round(json[item_id]['selling_price'], 2);
							if(json[item_id]['price_type_id']) $('price_type_id,'+item_id).value = json[item_id]['price_type_id'];
							if(json[item_id]['trade_discount_code']) $('tdc,'+item_id).update(json[item_id]['trade_discount_code']);
						}
						$('row_discount,'+item_id).update(discount);
						$('input_discount_per,'+item_id).value = discount;
						$('stock_balance2,'+item_id).value = sb2;
						row_recalc(item_id, false);
					}

					
					if(consignment_modules && masterfile_branch_region && consignment_multiple_currency && document.f_a['to_branch_id'] != undefined){
						foreign_variable_handler(true);
					}else{
						recalc_total();
					}
					//recalc_total();
					$('span_invoice_to_change_loading').update('');
				}
			});
		}
        return false;
	}    
	if(ele.value>0){
        $('srefresh').style.display='';
		$('refresh_btn').disabled=false;
	}else{
        $('srefresh').style.display='none';
		$('refresh_btn').disabled=true;
	}
	
}

function refresh_tables(){
	if(!check_branch()) return false;
	
	if (check_login()) {
        document.f_a.a.value = "refresh";
		document.f_a.target = "";
		document.f_a.submit();
    }
}

function check_branch(){
	if(document.f_a['to_branch_id'].value==''){
		alert('Please select invoice to.');
		return false;
	}
	if(document.f_a['branch_id'].value==document.f_a['to_branch_id'].value){
		alert('Cannot invoice to own branch.');
		return false;
	}
	return true;
}

function add_autocomplete(){
    var sku_item_id = $('sku_item_id').value;
    var sku_item_code = $('sku_item_code').value;
    if(!sku_item_id)    return false;
	var sku_code_list = [sku_item_id];
	clear_autocomplete();
    ajax_add_multiple_item(sku_code_list);
}

function ajax_add_multiple_item(sku_code_list){
    var param_str = Form.serialize(document.f_a) + '&a=ajax_add_item_row';
    var s = $H({'sku_code_list[]': sku_code_list}).toQueryString();
	$('autocomplete_sku_indicator').show();
	
	if(masterfile_branch_region && consignment_multiple_currency) param_str += "&currency_code="+branch_currency_code[document.f_a['to_branch_id'].value];

 	// insert new row
	ajax_request(phpself,{
		method:'post',
		parameters: param_str+'&'+s,
	    evalScripts: true,
		onFailure: function(m) {
		    $('autocomplete_sku_indicator').hide();
			alert(m.responseText);
			add_autocomplete_extra();
		},
		onSuccess: function (m) {
		    if (!/^(\s+)*<t/.test(m.responseText)&&m.responseText.trim()!=''){  // add failed
                alert(m.responseText);
                if($('btn_submit_multiple_add')){
                    $('btn_submit_multiple_add').value = 'Add';
                    $('btn_submit_multiple_add').disabled = false;
				}    
			}else{
                new Insertion.Bottom($('tbody_container'),m.responseText);
                if($('div_multiple_add_popup'))	default_curtain_clicked();
			}
			
		},
		onComplete: function(m){
			add_autocomplete_extra();
		}
	});
}

function submit_multi_add(ele){
	var sku_code_list = [];
	$$('#tbl_multi_add input.chx_sid_list').each(function(chx){
		if(chx.checked) sku_code_list.push(chx.value);
	});
	if(sku_code_list.length<=0) return false;
	ele.value = 'Adding...';
	ele.disabled = true;
	ajax_add_multiple_item(sku_code_list);
}

// function to run after finsih add items
function add_autocomplete_extra(){
    reset_row_no();
    $('autocomplete_sku_indicator').hide();
}

function reset_row_no(){
	var e = $('tbody_container').getElementsByClassName('no');
	var total_row=e.length;
	for(var i=0;i<e.length;i++)	{
 		$(e[i]).update((i+1)+'.');
	}
	$('autocomplete_sku').select();
}

/*function uom_change(value,id){
	var a = value.split(",");
	var old_cost = float($('cost_price,'+id).value)/float($('uom_fraction,'+id).value);
	var new_cost = old_cost*float(a[1]);
	var old_selling = float($('selling_price,'+id).value)/float($('uom_fraction,'+id).value);
	var new_selling = old_selling*float(a[1]);

	$('cost_price,'+id).value=round(new_cost,3);
    $('selling_price,'+id).value=round(new_selling,2);

	if(consignment_modules && consignment_multiple_currency){
		var old_foreign_cost=float($('foreign_cost_price,'+id).value)/float($('uom_fraction,'+id).value);
		var new_foreign_cost=old_foreign_cost*float(a[1]);
		$('foreign_cost_price,'+id).value=round(new_foreign_cost,3);
	}
	
	$('uom_id,'+id).value=a[0];
	$('uom_fraction,'+id).value=a[1];

	if(($('uom_fraction,'+id).value)=='1'){
		$('ctn,'+id).disable().value = '--';
	}
	else{
	    if($('ctn,'+id).value=='--')    $('ctn,'+id).value = '';
		$('ctn,'+id).enable();
	}
	row_recalc(id);
}*/

function delete_item(id){
 	if (!confirm('Remove this SKU from sheet?')) return;
 	var branch_id = document.f_a['branch_id'].value;
 	var cn_id = document.f_a['id'].value;
	ajax_request(phpself,{
		method:'post',
		parameters: 'a=ajax_delete_item&branch_id='+branch_id+'&cn_id='+cn_id+'&id='+id,
	    evalScripts: true,
		onFailure: function(m) {
			alert(m.responseText);
		},
		onSuccess: function (m) {
		    if(m.responseText.trim()=='OK'){
                Element.remove('tr_item,'+id);
				recalc_total();
				reset_row_no();
			}else{
                alert(m.responseText);
			}
    	}
	});
}

function check_has_foreign(){
	var hasforeign=(consignment_modules && masterfile_branch_region && consignment_multiple_currency && document.f_a['exchange_rate'] != undefined && !document.f_a['exchange_rate'].disabled)?1:0;
	
	if(hasforeign){
		if(branch_currency_code[document.f_a['to_branch_id'].value] && branch_currency_code[document.f_a['to_branch_id'].value] != "RM"){
	
		}else{
			hasforeign = 0;
		}
	}
	
	return hasforeign;
}

function row_recalc(id, need_recalc){
	if(need_recalc==undefined) need_recalc=true;
	
	var hasforeign=check_has_foreign();
	
	// check currency rate
	/*if(document.f_a['exchange_rate'] != undefined && !document.f_a['exchange_rate'].disabled && $('foreign_cost_price,'+id).value != 0){
		$('cost_price,'+id).value = round(float($('foreign_cost_price,'+id).value)*float(document.f_a['exchange_rate'].value), 3);
	}*/
	
	var row_qty = 0;
	var row_amt = 0;
	var selling = 0;
	var ctn = 0;
	var pcs = 0;
	var discount_amt = 0;
	var row_discount_amt = 0;
	
	if(hasforeign){
		var exchange_rate = (document.f_a['exchange_rate'].value==0)?1:document.f_a['exchange_rate'].value;
		if(document.f_a['exchange_rate'].value == 0) exchange_rate = 1;
		//var inp_cost_price = $('cost_price,'+id);
		//var foreign_cost_price=$('foreign_cost_price,'+id);
		
		$('cost_price,'+id).readOnly = true;
		$('foreign_cost_price,'+id).readOnly = false;
		
		if(is_under_gst){
			document.f_a['display_cost_price['+id+']'].readOnly = true;
		}
			
		/*if(branch_currency_code[document.f_a['to_branch_id'].value] && branch_currency_code[document.f_a['to_branch_id'].value] != "RM"){
			inp_cost_price.readOnly = true;
			foreign_cost_price.readOnly = false;
			
			if(is_under_gst){
				document.f_a['display_cost_price['+id+']'].readOnly = true;
			}
			
		}else{
			if(!branch_exchange_rate[document.f_a['to_branch_id'].value] && foreign_cost_price.value > 0 && inp_cost_price.value == 0) inp_cost_price.value = foreign_cost_price.value;
			inp_cost_price.readOnly = false;
			foreign_cost_price.readOnly = true;
			
			if(is_under_gst){
				document.f_a['display_cost_price['+id+']'].readOnly = false;
			}
		}*/
	}else{
		$('cost_price,'+id).readOnly = false;
		if($('foreign_cost_price,'+id))	$('foreign_cost_price,'+id).readOnly = true;
		
		if(is_under_gst){
			document.f_a['display_cost_price['+id+']'].readOnly = false;
		}
	}
	
	var fraction = float($('uom_fraction,'+id).value);
	var cost = float($('cost_price,'+id).value)/fraction;
	var selling = float($('selling_price,'+id).value)/fraction;

	var display_cost_price_is_inclusive = 0;
	var gst_rate = 0;
	if(is_under_gst){
		display_cost_price_is_inclusive = document.f_a['display_cost_price_is_inclusive['+id+']'].checked;
		gst_rate = float(document.f_a["gst_rate["+id+"]"].value);
	}
	
	var row_discount = $('input_discount_per,'+id).value;
	var disc1 = float(row_discount.split("+")[0]);
	var disc2 = 0;
	if(row_discount.split("+").length>1)	disc2 = float(row_discount.split("+")[1]);
	
	if(!$('ctn,'+id).disabled)	ctn = float($('ctn,'+id).value);
	pcs = float($('pcs,'+id).value);
	total_qty = (ctn*fraction) + pcs;
	$('row_qty,'+id).update(total_qty);
	$('row_selling,'+id).update(round(total_qty*selling, 2));
	
	row_amt = float(total_qty*cost);
	if(disc1){
        discount_amt = float(row_amt*(disc1/100));
        row_discount_amt += discount_amt;
        row_amt -= discount_amt;
	}
	if(disc2){
        discount_amt = float(row_amt*(disc2/100));
        row_discount_amt += discount_amt;
        row_amt -= discount_amt;
	}
	
	//row_discount_amt = float(round2(row_discount_amt));
	//row_amt = float(round2(row_amt-row_discount_amt));
	
	$('input_discount_amt,'+id).value = round(row_discount_amt, 2);
	$('row_amount,'+id).update(round(row_amt, 2));
	
	var row_foreign_disc_amt = 0;
	var row_foreign_amount = 0;
	var item_discount = row_discount;
	if(hasforeign){
		var cost_price=$('foreign_cost_price,'+id).value;

		if(is_under_gst){
			if(display_cost_price_is_inclusive){
				cost_price = cost_price / (100+gst_rate) * 100;
			}
		}
		row_foreign_amount=total_qty*(cost_price/fraction);
					
		if(item_discount){
			var disc=item_discount.split("+");
			for(i=0;i<disc.length;i++){
				var discount_amt = row_foreign_amount*(float(disc[i])/100);
				row_foreign_amount -= discount_amt;
				row_foreign_disc_amt += float(discount_amt);
			}
		}
		
		//row_foreign_amount = round(row_foreign_amount, 2);
		document.f_a["item_foreign_amt["+id+"]"].value = round(row_foreign_amount,2);
		document.f_a["item_foreign_amt2["+id+"]"].value = round(row_foreign_amount,2);
		

		var row_foreign_gst = 0;
		var row_foreign_gst_amt = row_foreign_amount;
		
		if (is_under_gst) {	
			//row_foreign_gst = float(row_foreign_amount*gst_rate/100);
			//row_foreign_amount = float(row_foreign_amount) + float(row_foreign_gst);
			
			row_foreign_gst_amt = float(round(row_foreign_amount * (100 + gst_rate) / 100,2));
			
			var row_foreign_amount_rounded = float(round(row_foreign_amount, 2));
			
			row_foreign_gst = float(round(row_foreign_gst_amt-row_foreign_amount_rounded, 2));
			
			document.f_a["item_foreign_gst["+id+"]"].value = round(row_foreign_gst,2);
			document.f_a["item_foreign_gst2["+id+"]"].value = round(row_foreign_gst,2);
		}
		
		document.f_a["item_foreign_gst_amt["+id+"]"].value = round(row_foreign_gst_amt,2);
		document.f_a["item_foreign_gst_amt2["+id+"]"].value = round(row_foreign_gst_amt,2);
		document.f_a["foreign_discount_amt["+id+"]"].value = round(row_foreign_disc_amt,2);
		document.f_a["item_foreign_disc_amt2["+id+"]"].value = 0;
		
		
		
		$('row_foreign_amount,'+id).innerHTML=round(row_foreign_gst_amt,2);
	}
	
	var row_gst = 0;
	var row_gst_amt = row_amt;
	
	if (is_under_gst) {
		var gst_rate = float(document.f_a["gst_rate["+id+"]"].value);
		row_gst_amt = row_amt * (100 + gst_rate) / 100;
		
		var row_amt_rounded = float(round(row_amt, 2));
		var row_gst_amt_rounded = float(round(row_gst_amt, 2));
		row_gst = float(round(row_gst_amt_rounded-row_amt_rounded, 2));
		
		$('item_gst_amt,'+id).update(row_gst_amt.toFixed(2));
		document.f_a["item_gst["+id+"]"].value = round(row_gst, 2);
		
		$('row_gst,'+id).update(round(row_gst, 2));
		
		document.f_a["item_gst2["+id+"]"].value = round(row_gst, 2);
	}
	
	document.f_a["item_amt["+id+"]"].value = round(row_amt, 2);
	
	document.f_a["item_gst_amt["+id+"]"].value = round(row_gst_amt, 2);
	document.f_a["item_gst_amt2["+id+"]"].value = round(row_gst_amt, 2);
	
	document.f_a["item_amt2["+id+"]"].value = round(row_amt, 2);
	document.f_a["item_disc_amt2["+id+"]"].value = 0;
		
	if(need_recalc)	recalc_total();
}

function recalc_total(){
	var total_ctn = 0;
	var total_pcs = 0;
	var total_amt = 0;
	var total_qty = 0;
	var total_selling = 0;
	var discount_amt = 0;
	var total_discount_amt = 0;
	
	var hasforeign=check_has_foreign();
	
	var discount = document.f_a['discount'].value;
	var disc1 = float(discount.split("+")[0]);
	var disc2 = 0;
	var total_item_amt = 0;
	var total_gst = 0;
	
	if(discount.split("+").length>1)	disc2 = float(discount.split("+")[1]);
	
	// ctn
	var inp_ctn = $$('#tbody_container input.ctn');
	for(var i=0; i<inp_ctn.length; i++){
		if(inp_ctn[i].value=='--')  continue;
		total_ctn += float(inp_ctn[i].value);
	}
	// pcs
	var inp_pcs = $$('#tbody_container input.pcs');
	for(var i=0; i<inp_pcs.length; i++){
		total_pcs += float(inp_pcs[i].value);
	}
	// amt
	var span_amt = $$('#tbody_container span.row_amt');
	for(var i=0; i<span_amt.length; i++){
		total_amt += float(span_amt[i].innerHTML);
	}
	
	// item final amt
	var inp_gst_amt = $$('#tbody_container input.row_gst_amt');
	for(var i=0; i<inp_gst_amt.length; i++){
		total_item_amt += float(inp_gst_amt[i].value);
	}
	
	// item gst
	var inp_gst = $$('#tbody_container input.row_item_gst');
	for(var i=0; i<inp_gst.length; i++){
		total_gst += float(inp_gst[i].value);
	}
	
	// selling
	var span_selling = $$('#tbody_container span.row_selling');
	for(var i=0; i<span_selling.length; i++){
		total_selling += float(span_selling[i].innerHTML);
	}
	
	// qty
	var span_qty = $$('#tbody_container span.row_qty');
	for(var i=0; i<span_qty.length; i++){
		total_qty += float(span_qty[i].innerHTML);
	}

	total_amt = float(round2(total_amt));
	total_selling = float(round2(total_selling));
	
	document.f_a['total_ctn'].value = total_ctn;
	document.f_a['total_pcs'].value = total_pcs;
	document.f_a['total_amount'].value = total_amt;
	document.f_a['total_selling'].value = total_selling;
	document.f_a['total_qty'].value = total_qty;
    document.f_a['disc_arr[0]'].value = disc1;
	document.f_a['disc_arr[1]'].value = disc2;
	
	$('span_total_ctn').update(total_ctn);
	$('span_total_pcs').update(total_pcs);

	/////////
	var sub_total_gross_amt = float(round(total_amt,2));
	var sub_total_gst_amt = float(round(total_gst,2));
	var sub_total_amt = float(round(total_item_amt,2));
	
	var gross_discount_amount = 0;
	var sheet_gst_discount = 0;
	var discount_amount = 0;
	
	var total_gross_amt = sub_total_gross_amt;
	var total_gst_amt = sub_total_gst_amt;
	var total_amount = sub_total_amt;
	
	var tr_item_list;
	show_sub_total = false;
	
	// sub total
	document.f_a['sub_total_gross_amt'].value = round(sub_total_gross_amt, 2);
	//if(is_under_gst)	document.f_a['sub_total_gst_amt'].value = round(sub_total_gst_amt, 2);
	document.f_a['sub_total_amt'].value = round(sub_total_amt, 2);
	$('span_subtotal_selling').update(total_selling.toFixed(2));
	$('span_subtotal_amt').update(sub_total_gross_amt.toFixed(2));
	if(is_under_gst){
		$('td_sub_total_gst').update(sub_total_gst_amt.toFixed(2));
		$('td_sub_total_gst_amount').update(sub_total_amt.toFixed(2));
	}	
	
	// sheet discount
	var discount_perc = "";
	var tmp_amt = total_amount;
	if(disc1){  // sheet discount 1
	    tmp_discount_amt = float(tmp_amt*(disc1/100));
	    discount_amount += tmp_discount_amt;
        tmp_amt -= tmp_discount_amt;
		discount_perc += disc1+"%";
	}
	if(disc2){  // further discount
	    tmp_discount_amt = float(tmp_amt*(disc2/100));
	    discount_amount += tmp_discount_amt;
        tmp_amt -= tmp_discount_amt;
		discount_perc += "+"+disc2+"%";
	}
	var p = (discount_amount * 100) / total_amount;
	
	discount_amount = float(round(discount_amount,2));
	if(discount_amount){
		show_sub_total = true;
		total_amount -= discount_amount;
	}
	
	gross_discount_amount = float(round(total_gross_amt * p /100,2));
	total_gross_amt -= gross_discount_amount;

	sheet_gst_discount = float(round(discount_amount-gross_discount_amount, 2));
	total_gst_amt = float(round(total_gst_amt-sheet_gst_discount,2));
	
	$('span_discount_amt').update(float(gross_discount_amount*-1).toFixed(2));
	if(is_under_gst){
		$('td_sheet_discount_gst_amount').update((discount_amount*-1).toFixed(2));
		$('td_sheet_discount_gst').update((sheet_gst_discount*-1).toFixed(2));
	}
	
	document.f_a['gross_discount_amount'].value = round(gross_discount_amount, 2);
	document.f_a['sheet_gst_discount'].value = round(sheet_gst_discount, 2);
	document.f_a['discount_amount'].value = round(discount_amount, 2);
	
	total_gross_amt = float(round(total_gross_amt, 2));
	total_amount = float(round(total_amount, 2));
	
	
	// total
	//console.log('total_gross_amt: '+total_gross_amt+' ,total_gst_amt: '+total_gst_amt+' ,total_amount: '+total_amount);
	
	$('span_total_amt').update(total_gross_amt.toFixed(2));
	if(is_under_gst){
		$('td_total_gst').update(total_gst_amt.toFixed(2));
		$('td_total_gst_amt').update(total_amount.toFixed(2));
	}
	
	document.f_a['total_gross_amt'].value = round(total_gross_amt,2);
	document.f_a['total_gst_amt'].value = round(total_gst_amt,2);
	document.f_a['total_amount'].value = round(total_amount,2);
	
	var remaining_sheet_discount_gross_amt = gross_discount_amount;
	var remaining_sheet_gst_discount = sheet_gst_discount;
	var remaining_sheet_discount_amt = discount_amount;
	
	// get all item row
	if(!tr_item_list) tr_item_list = $$('#tbody_container tr.tr_item');
	
	// loop for each row to calculate gross amt2, gst amt2, line total amt2
	for(var i=0,item_len = tr_item_list.length; i<item_len; i++){
		var tr = tr_item_list[i].id;
		var item_id = $(tr).readAttribute('item_id');

		var gst_rate = 0;
		var line_gross_amt = float(document.f_a["item_amt["+item_id+"]"].value);
		var line_gst_amt = 0;
		var line_amt = float(document.f_a["item_gst_amt["+item_id+"]"].value);

		if(is_under_gst){
			gst_rate = float(document.f_a["gst_rate["+item_id+"]"].value);
			line_gst_amt = float(document.f_a["item_gst["+item_id+"]"].value);
		}
		
		var line_gross_amt2 = line_gross_amt;
		var line_gst_amt2 = line_gst_amt;
		var line_amt2 = line_amt;
		var item_discount_amount2 = 0;

		if (p!= undefined) {
			line_amt2 = line_amt * ((100 - p) / 100);
			line_gross_amt2 = line_amt2 / ((100 + gst_rate) / 100);

			var line_amt2_rounded = float(round(line_amt2 ,2));
			var line_gross_amt2_rounded = float(round(line_gross_amt2 ,2));
			line_gst_amt2 = float(round(line_amt2_rounded-line_gross_amt2_rounded,2));
			
			item_discount_amount2 = line_amt - line_amt2_rounded;
		}
		
		line_gross_amt2 = float(round(line_gross_amt2,2));
		line_gst_amt2 = float(round(line_gst_amt2,2));
		line_amt2 = float(round(line_amt2,2));
		item_discount_amount2 = float(round(item_discount_amount2,2));
		
		remaining_sheet_discount_gross_amt = float(round(remaining_sheet_discount_gross_amt - (line_gross_amt - line_gross_amt2), 2));
		remaining_sheet_gst_discount = float(round(remaining_sheet_gst_discount - (line_gst_amt - line_gst_amt2), 2));
		remaining_sheet_discount_amt = float(round(remaining_sheet_discount_amt - (item_discount_amount2), 2));

		if(i == item_len-1){
			if(remaining_sheet_discount_gross_amt != 0){
				line_gross_amt2 -= remaining_sheet_discount_gross_amt;
				remaining_sheet_discount_gross_amt = 0;
			}
			if(remaining_sheet_gst_discount != 0){
				line_gst_amt2 -= remaining_sheet_gst_discount;
				remaining_sheet_gst_discount = 0;
			}
			if(remaining_sheet_discount_amt != 0){
				line_amt2 -= remaining_sheet_discount_amt;
				item_discount_amount2 += remaining_sheet_discount_amt;
				remaining_sheet_discount_amt = 0;
			}
		}
		
		document.f_a["item_amt2["+item_id+"]"].value = round(line_gross_amt2, 2);
		
		if(is_under_gst){
			document.f_a["item_gst2["+item_id+"]"].value = round(line_gst_amt2, 2);
		}
		
		document.f_a["item_gst_amt2["+item_id+"]"].value = round(line_amt2, 2);
		document.f_a["item_disc_amt2["+item_id+"]"].value = round(item_discount_amount2, 2);
	}
	
	//console.log('hasforeign: '+hasforeign);
	// foreign
	if(hasforeign){
		
		// sub total
		var sub_total_foreign_gross_amt = 0;
		var sub_total_gst_amt = 0;
		var sub_total_foreign_amt = 0;
		
		// discount
		var gross_foreign_discount_amount = 0;
		var sheet_foreign_gst_discount = 0;
		var foreign_discount_amount = 0;
		
		// total
		var total_foreign_gross_amt = 0;
		var total_foreign_gst_amt = 0;
		var total_foreign_amount = 0;
		
		// get all item row
		if(!tr_item_list) tr_item_list = $$('#tbody_container tr.tr_item');
		var item_len = tr_item_list.length;
		
		// loop for each row to calculate gross amt2, gst amt2, line total amt2
		for(var i=0,item_len = tr_item_list.length,len=item_len; i<len; i++){
			var tr = tr_item_list[i].id;
			var item_id = $(tr).readAttribute('item_id');
			
			var item_foreign_amt = float(round(document.f_a['item_foreign_amt['+item_id+']'].value, 2));
			var item_foreign_gst = 0;
			var item_foreign_gst_amt = item_foreign_amt;
			if(is_under_gst){
				item_foreign_gst = float(round(document.f_a['item_foreign_gst['+item_id+']'].value, 2));
				item_foreign_gst_amt = float(round(document.f_a['item_foreign_gst_amt['+item_id+']'].value, 2));
			}
			
			
			sub_total_foreign_gross_amt += item_foreign_amt;
			sub_total_foreign_amt += item_foreign_gst_amt;
		}
		sub_total_gst_amt = float(round(sub_total_foreign_amt-sub_total_foreign_gross_amt, 2));
		
		total_foreign_gross_amt = sub_total_foreign_gross_amt;
		total_foreign_gst_amt = sub_total_gst_amt;
		total_foreign_amount = sub_total_foreign_amt;
		
		// update sub total
		document.f_a['sub_total_foreign_gross_amt'].value = round(sub_total_foreign_gross_amt, 2);
		$('td_subtotal_foreign_amt').update(round(sub_total_foreign_amt, 2));
		document.f_a['sub_total_foreign_amt'].value=round(sub_total_foreign_amt, 2);
		
		// sheet discount
		
		var foreign_discount_amount = float(round(get_discount_amt(total_foreign_amount, discount_perc),2));
		total_foreign_amount -= foreign_discount_amount;

		gross_foreign_discount_amount = float(round(get_discount_amt(total_foreign_gross_amt, discount_perc),2));
		total_foreign_gross_amt -= gross_foreign_discount_amount;
		
		sheet_foreign_gst_discount = float(round(foreign_discount_amount-gross_foreign_discount_amount,2));
		total_foreign_gst_amt -= sheet_foreign_gst_discount;
		
		// update sheet discount
		document.f_a['gross_foreign_discount_amount'].value = gross_foreign_discount_amount;
		document.f_a['sheet_foreign_gst_discount'].value = round(sheet_foreign_gst_discount,2);
		document.f_a['foreign_discount_amount'].value = round(foreign_discount_amount,2);
		$('td_display_foreign_discount_amount').update((foreign_discount_amount*-1).toFixed(2));

		// total
		document.f_a['total_foreign_gross_amt'].value = round(total_foreign_gross_amt, 2);
		document.f_a['total_foreign_gst_amt'].value = round(total_foreign_gst_amt,2);
		document.f_a['total_foreign_amount'].value = round(total_foreign_amount,2);
		$('display_total_foreign_amount').update(total_foreign_amount.toFixed(2));
		
		// loop for each row to calculate gross amt2, gst amt2, line total amt2
		var remaining_gross_foreign_discount_amount = gross_foreign_discount_amount;
		var remaining_sheet_foreign_gst_discount = sheet_foreign_gst_discount;
		var remaining_foreign_discount_amount = foreign_discount_amount;
				
		for(var i=0,item_len = tr_item_list.length; i<item_len; i++){
			var tr = tr_item_list[i].id;
			var item_id = $(tr).readAttribute('item_id');

			var line_foreign_gross_amt = float(document.f_a["item_foreign_amt["+item_id+"]"].value);
			var line_foreign_gst_amt = 0
			var gst_rate = 0;
			var line_foreign_amt = line_foreign_gross_amt;
			if(is_under_gst){
				gst_rate = float(document.f_a["gst_rate["+item_id+"]"].value);
				line_foreign_gst_amt = float(document.f_a["item_foreign_gst["+item_id+"]"].value);
				line_foreign_amt = float(document.f_a["item_foreign_gst_amt["+item_id+"]"].value);
			}

			var line_foreign_gross_amt2 = line_foreign_gross_amt;
			var line_foreign_gst_amt2 = line_foreign_gst_amt;
			var line_foreign_amt2 = line_foreign_amt;
			var item_foreign_discount_amount2 = 0;
			
			if (p!= undefined) {
				line_foreign_amt2 = line_foreign_amt * ((100 - p) / 100);
				line_foreign_gross_amt2 = line_foreign_amt2 / ((100 + gst_rate) / 100);

				var line_foreign_amt2_rounded = float(round(line_foreign_amt2 ,2));
				var line_foreign_gross_amt2_rounded = float(round(line_foreign_gross_amt2 ,2));
				line_foreign_gst_amt2 = float(round(line_foreign_amt2_rounded-line_foreign_gross_amt2_rounded,2));
				
				item_foreign_discount_amount2 = line_foreign_amt - line_foreign_amt2_rounded;
			}
			
			line_foreign_gross_amt2 = float(round(line_foreign_gross_amt2,2));
			line_foreign_gst_amt2 = float(round(line_foreign_gst_amt2,2));
			line_foreign_amt2 = float(round(line_foreign_amt2,2));
			item_foreign_discount_amount2 = float(round(item_foreign_discount_amount2,2));

			remaining_gross_foreign_discount_amount = float(round(remaining_gross_foreign_discount_amount - (line_foreign_gross_amt - line_foreign_gross_amt2), 2));
			remaining_sheet_foreign_gst_discount = float(round(remaining_sheet_foreign_gst_discount - (line_foreign_gst_amt - line_foreign_gst_amt2), 2));
			remaining_foreign_discount_amount = float(round(remaining_foreign_discount_amount - (item_foreign_discount_amount2), 2));
			
			if(i == item_len-1){
				if(remaining_gross_foreign_discount_amount != 0){
					line_foreign_gross_amt2 -= remaining_gross_foreign_discount_amount;
					remaining_gross_foreign_discount_amount = 0;
				}
				if(remaining_sheet_foreign_gst_discount != 0){
					line_foreign_gst_amt2 -= remaining_sheet_foreign_gst_discount;
					remaining_sheet_foreign_gst_discount = 0;
				}
				if(remaining_foreign_discount_amount != 0){
					line_foreign_amt2 -= remaining_foreign_discount_amount;
					item_foreign_discount_amount2 += remaining_foreign_discount_amount;
					remaining_foreign_discount_amount = 0;
				}
			}
		
			document.f_a["item_foreign_amt2["+item_id+"]"].value = round(line_foreign_gross_amt2,2);
			
			if(is_under_gst){
				document.f_a["item_foreign_gst2["+item_id+"]"].value = round(line_foreign_gst_amt2,2);
			}
			
			document.f_a["item_foreign_gst_amt2["+item_id+"]"].value = round(line_foreign_amt2,2);
			document.f_a["item_foreign_disc_amt2["+item_id+"]"].value = item_foreign_discount_amount2;
		}
			
		
	}
	
}

function check_save(){
	if(check_branch())  return true;
	return false;
}

function do_save(){
	document.f_a.a.value='save';
	document.f_a.target = "";
	if(check_save()){
	
		center_div('wait_popup');
		curtain(true,'curtain2');
		Element.show('wait_popup');
	
		ajax_request(phpself,{
			method: 'post',
			parameters: Form.serialize(document.f_a)+'&a=check_tmp_item_exists',
			onComplete: function(e){
				if (e.responseText.trim() == 'OK') {
					document.f_a.submit();
					return;
				}
				else {
					Element.hide('wait_popup');
					curtain(false,'curtain2');
					alert(e.responseText.trim());
					return;
				}
			}
		});
	}
}

function discount_changed(){
    var discount = document.f_a['discount'].value.trim();
    var discount_format = /^\d+(\.\d+){0,1}(\+\d+(\.\d+){0,1}){0,1}$/;
	if(!discount_format.test(discount)){
        document.f_a['discount'].value = '';
        discount = '';
	} 

	if($('span_sheet_discount')){
		if(discount){
	    	/*var disc1 = round(discount.split("+")[0], 2);
			var str = '(-'+disc1+'%)';
			if(discount.split("+").length>1)	str += '<br>(-'+round(discount.split("+")[1],2)+'%)';
            $('div_sheet_discount').update(str);*/
            $('span_sheet_discount').update(discount+'%');
            $('tr_sheet_discount').show();
		}  
		else{
            $('span_sheet_discount').update('');
            $('tr_sheet_discount').hide();
		}    

		recalc_total();
	}
}

function do_delete(){
	if (check_login()) {
		document.f_a.reason.value = '';
		var p = prompt('Enter reason to Delete :');
		if (p==null || p.trim()=='') return;
		document.f_a.reason.value = p;
		if (confirm('Delete this sheet?')){
			document.f_a.a.value = "delete";
			document.f_a.submit();
		}
	}
	return;
}

function do_confirm(){
	if (check_login()) {

		if(check_save()){
			if (confirm('Finalise and submit for approval?')){

				center_div('wait_popup');
				curtain(true,'curtain2');
				Element.show('wait_popup');

				new Ajax.Request(phpself,{
					method: 'post',
					parameters: Form.serialize(document.f_a)+'&a=check_tmp_item_exists',
					onComplete: function(e){
						if (e.responseText.trim() == 'OK') {
							document.f_a.a.value = "confirm";
							document.f_a.target = "";
							document.f_a.submit();
							return;
						}
						else {
							Element.hide('wait_popup');
							curtain(false,'curtain2');
							alert(e.responseText.trim());
							return;
						}
					}
				});
			}
		}
	}
}

function do_reset(){
	if (check_login()) {

		document.f_do_reset['reason'].value = '';
		var p = prompt('Enter reason to Reset :');
		if (p==null || p.trim()=='' ) return false;
		document.f_do_reset['reason'].value = p;

		if(!confirm('Are you sure to reset?'))  return false;

		document.f_do_reset.submit();
	}
	return false;
}

foreign_variable_handler = function(need_recalc){

	if ($('div_sheets') == undefined) return; // if no items, return
	
	var to_branch_id = document.f_a['to_branch_id'].value;

	if(!to_branch_id || branch_currency_code[to_branch_id] == ""){
		$('span_p_currency_code').update("RM");
		$('span_sp_currency_code').update("RM");
		$('span_sp_amt_currency_code').update("RM");
		$('span_amt_currency_code').update("RM");
	}else{
		$('span_p_currency_code').update(branch_currency_code[to_branch_id]);
		$('span_sp_currency_code').update(branch_currency_code[to_branch_id]);
		$('span_sp_amt_currency_code').update(branch_currency_code[to_branch_id]);
		$('span_amt_currency_code').update(branch_currency_code[to_branch_id]);
	}
	
	if(!consignment_multiple_currency || !to_branch_id || branch_currency_code[to_branch_id] == "" || branch_currency_code[to_branch_id] == "RM" ){
		//document.f_a['exchange_rate'].readOnly = true;
		//document.f_a['exchange_rate'].disabled = false;
		$('foreign_price').style.display = "none";
		$('foreign_ttl_amt').style.display = "none";
		$$("#div_sheets .foreign_cost_price").invoke("hide");
		$$("#div_sheets .row_foreign_amount").invoke("hide");
		$$("#div_sheets #td_subtotal_foreign_amt").invoke("hide");
		$$("#div_sheets .total_foreign_amount").invoke("hide");
		$$("#div_sheets #td_display_foreign_discount_amount").invoke("hide");
		var ttl_colspan = document.f_a['colspan_length'].value;
		$("td_sub_total").colSpan = float(ttl_colspan);
		$("td_discount").colSpan = float(ttl_colspan);
		$("td_total").colSpan = float(ttl_colspan)-1;
		
		// remove non_editable class
		$$('#div_sheets input.inp_cost_price').each(function(inp){
			$(inp).removeClassName('non_editable');
		});
	}else{
		//document.f_a['exchange_rate'].readOnly = false;
		$('foreign_price').style.display = "";
		$('foreign_ttl_amt').style.display = "";
		$$("#div_sheets .foreign_cost_price").invoke("show");
		$$("#div_sheets .row_foreign_amount").invoke("show");
		$$("#div_sheets #td_subtotal_foreign_amt").invoke("show");
		$$("#div_sheets .total_foreign_amount").invoke("show");
		$$("#div_sheets #td_display_foreign_discount_amount").invoke("show");
		var ttl_colspan = document.f_a['colspan_length'].value;
		$("td_sub_total").colSpan = float(ttl_colspan)+1;
		$("td_discount").colSpan = float(ttl_colspan)+1;
		$("td_total").colSpan = float(ttl_colspan);
		
		// add non_editable class
		$$('#div_sheets input.inp_cost_price').each(function(inp){
			if(!$(inp).hasClassName('non_editable')){
				$(inp).addClassName('non_editable');
			}
		});
	}

	if(need_recalc != undefined) calc_all_items();
	
}

/*foreign_variable_recalc = function(){
	
	total_foreign_amt = 0, total_gross_foreign_amt = 0;
	if(document.f_a['exchange_rate'] == undefined) return;
	if(document.f_a['exchange_rate'].disabled)	return;
	
	var exchange_rate = document.f_a['exchange_rate'].value;
	if(document.f_a['exchange_rate'].value == 0){
		exchange_rate = 1;
	}

	var total_ctn = 0, total_pcs = 0, total_qty = 0, total_selling = 0, total_amount = 0, discount_amt = 0;
	var total_discount_amt = 0;
	
	var discount = document.f_a['discount'].value;
	var disc1 = float(discount.split("+")[0]);
	var disc2 = 0;
	if(discount.split("+").length>1)	disc2 = float(discount.split("+")[1]);

	// foreign amt
	var inp_amt = $$('#tbody_container span.row_foreign_amt');
	for(var i=0; i<inp_amt.length; i++){
		total_foreign_amt += float(inp_amt[i].innerHTML);
	}
	
	if(is_under_gst){
		// gross foreign amt
		var inp_amt = $$('#tbody_container input.item_foreign_gross_amt');
		for(var i=0; i<inp_amt.length; i++){
			total_gross_foreign_amt += float(inp_amt[i].value);
		}
	}

	// sub total
	total_foreign_amt = float(round2(total_foreign_amt));
	//console.log("total_foreign_amount: "+total_foreign_amt);
	$('td_subtotal_foreign_amt').update(total_foreign_amt.toFixed(2));
	document.f_a['sub_total_foreign_gross_amt'].value = total_foreign_amt;
	
	var total_foreign_amount = total_foreign_amt;
	var total_gross_foreign_amount = total_gross_foreign_amt;
	var total_foreign_discount_amt = 0, total_foreign_gross_discount_amt = 0, foreign_gross_discount_amt = 0;
	var discount_perc = "";
	document.f_a['sub_total_foreign_amt'].value=round(total_foreign_amount,2);

	if(disc1){  // sheet discount 1
		foreign_discount_amt = float(round(total_foreign_amount*(disc1/100), 2));
		total_foreign_discount_amt += foreign_discount_amt;
		total_foreign_amount -= foreign_discount_amt;
		
		if(is_under_gst){
			foreign_gross_discount_amt = float(round(total_gross_foreign_amt*(disc1/100), 2));
			total_foreign_gross_discount_amt += foreign_gross_discount_amt;
			total_gross_foreign_amt -= foreign_gross_discount_amt;
		}
		
		discount_perc += disc1+"%";
	}
	if(disc2){  // further discount
		foreign_discount_amt = float(round(total_foreign_amount*(disc2/100), 2));
		total_foreign_discount_amt += foreign_discount_amt;
		total_foreign_amount -= foreign_discount_amt;
		discount_perc += "+"+disc2+"%";
		
		if(is_under_gst){
			foreign_gross_discount_amt = float(round(total_gross_foreign_amt*(disc2/100), 2));
			total_foreign_gross_discount_amt += foreign_gross_discount_amt;
			total_gross_foreign_amt -= foreign_gross_discount_amt;
		}
	}

	$('td_display_foreign_discount_amount').update((total_foreign_discount_amt*-1).toFixed(2));
	document.f_a['foreign_discount_amount'].value = round(total_foreign_discount_amt, 2);
	total_foreign_amount = round(total_foreign_amount, 2);
	$('display_total_foreign_amount').update(total_foreign_amount);
	document.f_a['total_foreign_amount'].value = round(total_foreign_amount,2);
	
	if(is_under_gst){
		var total_foreign_gst_amt = 0, sheet_discount_foreign_discount_amt = 0, total_gross_foreign_discount_amt = 0, total_foreign_gst_amt = 0;
		document.f_a['gross_foreign_discount_amount'].value = foreign_gross_discount_amt;
		
		document.f_a['sub_total_foreign_gross_amt'].value = round(total_gross_foreign_amount, 2);
		document.f_a['total_foreign_gross_amt'].value = round(float(total_gross_foreign_amount)-float(foreign_gross_discount_amt), 2);
		
		// foreign amt after gst
		var span_foreign_gst_amt = $$('#tbody_container span.row_foreign_amt');
		for(var i=0; i<span_foreign_gst_amt.length; i++){
			total_foreign_gst_amt += float(span_foreign_gst_amt[i].innerHTML);
		}
		total_foreign_amt=total_foreign_gst_amt;
	
		// add sub total for GST amt
		sheet_discount_foreign_gross_amt = float(round(get_discount_amt(total_gross_foreign_amount, discount_perc),2));
		$('td_subtotal_foreign_amt').value=round(total_foreign_amt, 2);
		document.f_a['sub_total_foreign_amt'].value=round(total_foreign_amt, 2);

		// calculate sheet discount
		var sheet_foreign_discount_amt = 0;
		if(sheet_discount_foreign_gross_amt){
			var p = (sheet_discount_foreign_gross_amt * 100) / total_gross_foreign_amount;

			total_gross_foreign_amount -= sheet_discount_foreign_gross_amt;

			sheet_foreign_discount_amt = round(total_foreign_amt * p /100, 2);
			total_foreign_amt -= sheet_foreign_discount_amt;

			document.f_a['foreign_discount_amount'].value = round(sheet_foreign_discount_amt,2);

			$('td_display_foreign_discount_amount').update((sheet_foreign_discount_amt*-1).toFixed(2));
		}

		document.f_a['total_foreign_amount'].value = round(total_foreign_amt,2);
		//$('td_sheet_discount_gst').update((sheet_discount_foreign_gross_amt-sheet_foreign_discount_amt).toFixed(2));
		//$('td_total_gst').update((total_foreign_amt-total_foreign_gross_amt).toFixed(2));
		//$('td_total_gst_amt').update(total_foreign_amt.toFixed(2));
	
		// get all item row
		var tr_item_list = $$('#tbody_container input.tr_items');

		// loop for each row to calculate gross amt2, gst amt2, line total amt2
		for(var i=0,len=tr_item_list.length; i<len; i++){
			var tr = tr_item_list[i].id;
			var item_id = $(tr).readAttribute('item_id');

			var gst_rate = float(document.f_a["gst_rate["+item_id+"]"].value);
			var line_foreign_gross_amt = float(document.f_a["item_foreign_amt["+item_id+"]"].value);
			var line_foreign_gst_amt = float(document.f_a["item_foreign_gst["+item_id+"]"].value);
			var line_foreign_amt = float(document.f_a["item_foreign_gst_amt["+item_id+"]"].value);

			var line_foreign_gross_amt2 = line_foreign_gross_amt;
			var line_foreign_gst_amt2 = line_foreign_gst_amt;
			var line_foreign_amt2 = line_foreign_amt;
			var item_discount_amount2 = 0;

			if (p!= undefined) {
				line_foreign_amt2 = line_foreign_amt * ((100 - p) / 100);
				line_foreign_gross_amt2 = line_foreign_amt2 / ((100 + gst_rate) / 100);
				line_foreign_gst_amt2 = line_foreign_amt2 - line_foreign_gross_amt2;

				item_discount_amount2=round(line_foreign_amt - line_foreign_amt2,4);
			}

			document.f_a["item_foreign_amt2["+item_id+"]"].value = round(line_foreign_gross_amt2,4);
			document.f_a["item_foreign_gst2["+item_id+"]"].value = round(line_foreign_gst_amt2,4);
			document.f_a["item_foreign_gst_amt2["+item_id+"]"].value = round(line_foreign_amt2,4);
			document.f_a["item_foreign_disc_amt2["+item_id+"]"].value = item_discount_amount2;
		}
		
		document.f_a['total_foreign_gst_amt'].value = round((total_foreign_amt-total_gross_foreign_amount),2);
		document.f_a['sheet_foreign_gst_discount'].value = round((sheet_foreign_discount_amt-sheet_discount_foreign_gross_amt),2);
	}
}*/

/*function row_recalc_foreign(id){
	if(document.f_a['exchange_rate'] == undefined) return;
	if(document.f_a['exchange_rate'].disabled)	return;
	row_qty = 0, row_amt = 0, cost_price = 0, row_foreign_amt = 0;
	var discount_amt = 0;
	var total_foreign_amount = 0;
	row_foreign_disc_amt = 0;
	
	var exchange_rate = (document.f_a['exchange_rate'].value==0)?1:document.f_a['exchange_rate'].value;
	if(document.f_a['exchange_rate'].value == 0) exchange_rate = 1;
	var last_cost_id = $('cost_price,'+id);
	//if(document.f_a['foreign_cost_price['+id+']'].value == 0) document.f_a['foreign_cost_price['+id+']'].value = document.f_a['cost_price['+id+']'].value
	var foreign_cost_price=document.f_a['foreign_cost_price['+id+']'].value;
	var fraction=document.f_a['uom_fraction['+id+']'].value;
	var qty_ctn=document.f_a['ctn['+id+']'].value;
	var qty_pcs=document.f_a['pcs['+id+']'].value;
	var item_discount=document.f_a['discount_per['+id+']'].value;
	
	if(branch_currency_code[document.f_a['branch_id'].value] && branch_currency_code[document.f_a['branch_id'].value] != "RM"){
		if(foreign_cost_price.value == 0) foreign_cost_price.value = last_cost_id.value;
		last_cost_id.value = round(foreign_cost_price.value*exchange_rate, 3);
		last_cost_id.readOnly = true;
		foreign_cost_price.readOnly = false;
	}else{
		if(!branch_exchange_rate[document.f_a['branch_id'].value] && foreign_cost_price.value > 0 && last_cost_id.value == 0) last_cost_id.value = foreign_cost_price.value;
		last_cost_id.readOnly = false;
		foreign_cost_price.readOnly = true;
	}

	row_qty=int((float(qty_ctn)*fraction)+(float(qty_pcs)));
	row_foreign_amount=round(row_qty*(foreign_cost_price/fraction),2);
	row_foreign_amt=row_foreign_amount;
	
	if(item_discount){
		var disc=item_discount.split("+");
		for(i=0;i<disc.length;i++){
			var discount_amt = row_foreign_amt*(float(disc[i])/100);
			row_foreign_amount -= discount_amt;
			row_foreign_amt-=discount_amt;
			row_foreign_disc_amt = float(discount_amt);
		}
	}
	
	row_foreign_amount = round(row_foreign_amount, 2);
	document.f_a["item_foreign_amt["+id+"]"].value = row_foreign_amount;
	document.f_a["foreign_discount_amt["+id+"]"].value = round(row_foreign_disc_amt,2);
	
	if (is_under_gst) {	
		var gst_rate = float(document.f_a["gst_rate["+id+"]"].value);
		row_foreign_gst = float(round(row_foreign_amount*gst_rate/100,2));
		row_foreign_amount = float(row_foreign_amount) + float(row_foreign_gst);
		
		document.f_a["item_foreign_gst["+id+"]"].value = row_foreign_gst;
		document.f_a["item_foreign_gst_amt["+id+"]"].value = round(row_foreign_amount,2);
	}
			
	$('row_foreign_amount,'+id).innerHTML=round(row_foreign_amount,2);
}*/

// function when do date changed
function on_date_changed(){
	// get the object
	var inp = document.f_a['date'];
	// check max/min limit
	upper_lower_limit(inp);
	// check gst
	if(enable_gst)	check_gst_date_changed();
}

// function when do date is changed
function check_gst_date_changed(){
	var allow_gst = false;

	// gst is not enable
	if(!enable_gst)	return;

	// gst is active and branch got register
	if(gst_is_active && branch_gst_register_no){
		if(skip_gst_validate){
			allow_gst = true;
		}else{
			// got gst start date
			if(global_gst_start_date && branch_gst_start_date){
				// get Date
				var do_date = document.f_a["date"].value.trim();

				if(do_date){
					// check Date
					if(strtotime(do_date) >= strtotime(global_gst_start_date) && strtotime(do_date) >= strtotime(branch_gst_start_date)){
						allow_gst = true;
					}
				}
			}
		}
	}

	if(allow_gst){
		// date have gst
		if(!is_under_gst)	need_refresh_sheet();
	}else{
		// date no gst
		if(is_under_gst)	need_refresh_sheet();
	}
}

function on_item_gst_changed(sel, item_id){
	// update the selected gst
	update_selected_gst(item_id);

	// recalculate row
	row_recalc(item_id);
}

function need_refresh_sheet(){
	$('srefresh').style.display='';
	$('refresh_btn').disabled=false;
	$('refresh_btn').show();
	$('div_sheets').hide();
	$('p_submit_btn').hide();
}

function update_selected_gst(item_id){
	document.f_a["gst_id["+item_id+"]"].value = "";
	document.f_a["gst_code["+item_id+"]"].value = "";
	document.f_a["gst_rate["+item_id+"]"].value = "";
	document.f_a["gst_indicator["+item_id+"]"].value = "";

	var sel = document.f_a['item_gst_sel['+item_id+']'];

	if(sel.selectedIndex >= 0){
		// got select
		var opt = sel.options[sel.selectedIndex];
		var gst_id = $(opt).readAttribute("gst_id");
		var gst_code = $(opt).readAttribute("gst_code");
		var gst_rate = $(opt).readAttribute("gst_rate");
		var gst_indicator = $(opt).readAttribute("gst_indicator");

		document.f_a["gst_id["+item_id+"]"].value = gst_id;
		document.f_a["gst_code["+item_id+"]"].value = gst_code;
		document.f_a["gst_rate["+item_id+"]"].value = gst_rate;
		document.f_a["gst_indicator["+item_id+"]"].value = gst_indicator;
	}
}

calc_all_items=function(){
	var e = $('tbody_container').getElementsByClassName('tr_items');
	for(var i=0;i<e.length;i++){
		var item_id = $(e[i]).readAttribute('item_id');
		row_recalc(item_id, false);
	}
	recalc_total();
}

function on_export_clicked(obj){
	if(obj.checked == true){ // lock all tax code selection
		var tr_gst_code_list = $$('#tbody_container select.item_gst_slt');
		var all_rows = tr_gst_code_list.length;

		if(all_rows > 0){
			$A(tr_gst_code_list).each(
				function (r,idx){
					var item_id = $(r).readAttribute('item_id');
					$(r).value = gst_export;
					update_selected_gst(item_id);
					r.disabled = true;
					row_recalc(item_id);
				}
			);
		}
	}else{
		var tr_gst_code_list = $$('#tbody_container select.item_gst_slt');
		var all_rows = tr_gst_code_list.length;

		if(all_rows > 0){
			$A(tr_gst_code_list).each(
				function (r,idx){
					r.disabled = false;
				}
			);
		}
	}
}

function toggle_process_gst_price(id){
	showdiv('div_process_gst_price');
	center_div('div_process_gst_price');
	$("pgp_item_id").value = id;
	
	// update label for gst rate 
	var gst_rate = document.f_a['gst_rate['+id+']'].value;
	if(gst_rate > 0) $("span_pgp_gst_rate").update(gst_rate);
	else $("span_pgp_gst_rate").update('0');
	$("pgp_gst_price").value = "";
	$("pgp_gst").value = "";
	$("pgp_price").value = "";
	$("pgp_gst_price").focus();
}

function process_gst_price(obj){
	extractNumber(obj, 2, 0);
	
	var gst_price = float($("pgp_gst_price").value);
	var id = $("pgp_item_id").value;
	var gst_rate = float(document.f_a['gst_rate['+id+']'].value);
	
	var gst = float(round(gst_price / float(gst_rate+100) * gst_rate, 2));
	$("pgp_gst").value = round(gst, 2);
	$("pgp_price").value = round(gst_price - gst, 2);
}

function process_gst_price_clicked(){
	hidediv('div_process_gst_price');
	
	var id = $("pgp_item_id").value;
	document.f_a['cost_price['+id+']'].value = $("pgp_price").value;
	row_recalc(id);
}

function price_onkeypress(event){
	if (event == undefined) event = window.event;
	if(event.keyCode==13){  // enter
		process_gst_price_clicked();
	}
}

CN_MODULE = {
	f: undefined,
	initilize: function(){
		this.f = document.f_a;
	},
	// function when user toggle price is inclusive tax
	display_cost_price_is_inclusive_changed: function(item_id){
		this.item_row_changed(item_id);
	},
	// function when user change display cost price
	display_cost_price_changed: function(item_id){
		this.item_row_changed(item_id);
	},
	// function when user change cost price
	cost_price_changed: function(item_id, need_round){
		if(need_round){
			mf(this.f['cost_price['+item_id+']'],3);
		}
		this.item_row_changed(item_id);
	},
	// function to calculate real cost price from display cost price
	calculate_real_cost_price: function(item_id){
		//console.log('calculate_real_cost_price');
		// get the display cost price
		var inp_display_cost_price = this.f['display_cost_price['+item_id+']'];
		// round price to 3
		mf(inp_display_cost_price, 3);
		
		var display_cost_price = float(round(inp_display_cost_price.value,3));
		
		// not allow negative
		if(display_cost_price<0){
			display_cost_price = 0;
			inp_display_cost_price.value = 0;
		}
		var cost_price = display_cost_price;
		
		// check display cost price inclusive
		if(this.f['display_cost_price_is_inclusive['+item_id+']'].checked){
			// is inclusive tax
			// calculate before tax price
			var gst_rate = float(this.f["gst_rate["+item_id+"]"].value);
			if(gst_rate>0){
				cost_price = display_cost_price / (100+gst_rate) * 100;
			}
			$('div_cost_price_info-'+item_id).show();
		}else{
			// exclusive tax
			$('div_cost_price_info-'+item_id).hide();
		}
		
		// display cost price to label
		this.f['cost_price['+item_id+']'].value = cost_price;
		$('span_cost_price_label-'+item_id).update(round(cost_price,4));
	},
	// item row changed
	item_row_changed: function(item_id){
		//console.log('item_row_changed');
		// calculate real cost price
		if(is_under_gst){
			this.calculate_real_cost_price(item_id);
		}
		
		// recalculate row total
		this.item_row_recal(item_id);
	},
	// function to recal item row
	item_row_recal: function(item_id){
		row_recalc(item_id);
	},
	// function when user change row gst
	item_gst_changed: function(item_id){
		// update the selected gst
		update_selected_gst(item_id);
			
		// recalculate row
		this.item_row_changed(item_id);
	},
	// function when user change item uom
	item_uom_changed: function(item_id){
		var sel = $('sel_uom'+item_id);
		var a = sel.value.split(",");
		var old_fraction = float($('uom_fraction,'+item_id).value);
		var old_cost;
		var new_cost;
				
		// check old fraction
		if(is_under_gst){
			old_cost=float(this.f['display_cost_price['+item_id+']'].value)/old_fraction;
			new_cost=old_cost*float(a[1]);
			
			// change new cost
			this.f['display_cost_price['+item_id+']'].value = round(new_cost, 3);
		}else{
			
			old_cost=float(this.f['cost_price['+item_id+']'].value)/old_fraction;
			new_cost=old_cost*float(a[1]);
			
			// change new cost
			this.f['cost_price['+item_id+']'].value = round(new_cost, 3);
		}
		
		
		// foreign currency
		if(consignment_modules && consignment_multiple_currency){
			var old_foreign_cost=float($('foreign_cost_price,'+item_id).value)/old_fraction;
			var new_foreign_cost=old_foreign_cost*float(a[1]);
			$('foreign_cost_price,'+item_id).value=round(new_foreign_cost,3);
		}
		
		// update new uom
		$('uom_id,'+item_id).value=a[0];
		$('uom_fraction,'+item_id).value=a[1];
		
		// change ctn/pcs
		this.check_row_ctn_pcs_input(item_id);
		
		// recalulate row
		this.item_row_changed(item_id);

		// calc foreign
		//if(consignment_modules && consignment_multiple_currency && do_type =='transfer') foreign_variable_recalc();
	},
	// function to check row ctn/pcs input
	check_row_ctn_pcs_input: function(item_id){
		var inp_qty_ctn_list = $('tr_item,'+item_id).getElementsBySelector('input.inp_qty_ctn');
		var uom_fraction = float($('uom_fraction,'+item_id).value);
		
		for(var i=0,len=inp_qty_ctn_list.length; i<len; i++){
			var inp = inp_qty_ctn_list[i];
			if(uom_fraction == 1){
				inp.value = '--';
				inp.disabled = true;
			}else{
				inp.disabled = false;
				if(inp.value == '--' || inp.value == '-'){
					inp.value = '';
				}
			}
			
		}
	},
	// function when user change foreign cost price
	foreign_cost_price_changed: function(item_id){
		var exchange_rate = (document.f_a['exchange_rate'].value==0)? 1 : document.f_a['exchange_rate'].value;
		var inp_foreign = document.f_a['foreign_cost_price['+item_id+']'];
		var inp_display_cost_price = document.f_a['display_cost_price['+item_id+']'];
		
		mf(inp_foreign, 3);
		if(inp_foreign.value == 0) inp_foreign.value = inp_cost_price.value;
		else{
			if(is_under_gst){
				inp_display_cost_price.value = round(inp_foreign.value*exchange_rate, 3);
			}else{
				this.f['cost_price['+item_id+']'].value = round(inp_foreign.value*exchange_rate, 3);
			}
		}
		this.cost_price_changed(item_id);
	}
}
{/literal}
</script>

<div id=wait_popup style="display:none;position:absolute;z-index:10000;background:#fff;border:1px solid #000;padding:5px;width:200;height:100">
	<p align=center>
		Please wait..<br /><br /><img src="ui/clock.gif" border="0" />
	</p>
</div>

<div style="position: absolute; z-index: 20000; border: 2px solid rgb(206, 0, 0); background-color: rgb(255, 255, 255); background-image: url(&quot;/ui/ndiv.jpg&quot;); background-repeat: repeat-x; padding: 0pt ! important; top: 208px; left: 540px; display:none;" class="curtain_popup" id="div_process_gst_price">
	<div style="border: 2px ridge rgb(206, 0, 0); color: white; background-color: rgb(206, 0, 0); padding: 2px; cursor: default;" id="div_process_gst_price_header"><span>Price Calculation</span>
		<span style="float: right;">
			<img align="absmiddle" class="clickable" onclick="default_curtain_clicked();" src="/ui/closewin.png">
		</span>
	</div>
	<br />
	<table cellspacing="0" border="0" padding="0">
		<tr>
			<td>Price Included GST:</td>
			<td><input type="text" size="8" id="pgp_gst_price" class="r" onkeyup="process_gst_price(this);" onkeypress="price_onkeypress(event);"></td>
		</tr>
		<tr>
			<td>GST (<span id="span_pgp_gst_rate"></span>%)</td>
			<td><input type="text" size="8" id="pgp_gst" class="r" readonly></td>
		</tr>
		<tr>
			<td>Price Excluded GST:</td>
			<td><input type="text" size="8" id="pgp_price" class="r" readonly></td>
		</tr>
	</table>
	<p align="center">
		<input type="hidden" id="pgp_item_id" value="" />
		<input type=button value="Confirm" onclick="process_gst_price_clicked()">
		<input type=button value="Back" onclick="default_curtain_clicked()">
	</p>
</div>

<form name="f_do_reset" method="post" style="display:none;">
<input type=hidden name="a" value="do_reset">
<input type=hidden name="branch_id" value="{$form.branch_id}">
<input type=hidden name="id" value="{$form.id}" >
<input type=hidden name="curr_date" value="{$form.date}" >
<input type=hidden name=reason value="">
</form>

<!-- end of special div -->
{if !$form.approved}
<h1>{$sheet_name|lower|capitalize} {if $form.id<$time_value}(ID#{$form.id}){else}(New){/if}</h1>
{else}
<h1>{$sheet_name|lower|capitalize} {if $form.inv_no}({$form.inv_no}){else}{if $form.id<$time_value}(ID#{$form.id}){/if}{/if}</h1>
{/if}

<h3>Status:
{if $form.approved}
	Fully Approved
{elseif $form.status == 1}
	In Approval Cycle
{elseif $form.status == 5}
	Cancelled
{elseif $form.status == 4}
	Terminated
{elseif $form.status == 3}
	In Approval Cycle (KIV)
{elseif $form.status == 2}
	Rejected
{elseif $form.status == 0}
	Draft
{/if}
</h3>
{include file=approval_history.tpl}

{if $form.approval_screen}
<form name="f_b" method=post>
<input type=hidden name=branch_id value="{$form.branch_id}" />
<input type=hidden name=id value="{$form.id}" />
<input type=hidden name=comment value="">
<input type=hidden name=a value="approve">
<input type=hidden name=approvals value="{$form.approvals}">
<input type=hidden name=approval_history_id value="{$form.approval_history_id}" />
<input type=hidden name="curr_date" value="{$form.date}" >
{if $approval_on_behalf}
<input type="hidden" name="on_behalf_of" value="{$approval_on_behalf.on_behalf_of}" />
<input type="hidden" name="on_behalf_by" value="{$approval_on_behalf.on_behalf_by}" />
{/if}
</form>
{/if}

<form name="f_a" method=post ENCTYPE="multipart/form-data">
<div class="stdframe" style="background:#fff">
<h4>General Informations</h4>

{if $errm.top}
<div id=err><div class=errmsg><ul>
{foreach from=$errm.top item=e}
<li> {$e}
{/foreach}
</ul></div></div>
{else}
<div id=err></div>
{/if}

<input type="hidden" name="a" value="save" />
<input type="hidden" name="branch_id" value="{$form.branch_id|default:$sessioninfo.branch_id}" />
<input type="hidden" name="id" value="{$form.id}" />
<input type="hidden" name="inv_no" value="{$form.inv_no}" />
<input type="hidden" name="total_ctn" value="{$form.total_ctn}" />
<input type="hidden" name="total_pcs" value="{$form.total_pcs}" />
<input type="hidden" name="total_amount" value="{$form.total_amount}" />
<input type="hidden" name="total_foreign_amount" id="total_foreign_amount" value="{$form.total_foreign_amount}">
<input type="hidden" name="total_qty" value="{$form.total_qty}" />
<input type="hidden" name="approval_history_id" value="{$form.approval_history_id}" />
<input type="hidden" name="reason" />
<input type="hidden" name="disc_arr[0]" value="{$form.disc_arr.0}" />
<input type="hidden" name="disc_arr[1]" value="{$form.disc_arr.1}" />
<input type="hidden" name="username" value="{$form.username}" />
<input type="hidden" name="total_selling" value="{$form.total_selling}" />
<input type="hidden" name="discount_amount" value="{$form.discount_amount}" />
<input type="hidden" name="gross_discount_amount" value="{$form.gross_discount_amount}" />
<input type="hidden" name="foreign_discount_amount" value="{$form.foreign_discount_amount}" />
<input type="hidden" name="is_under_gst" value="{$form.is_under_gst}" />
<input type="hidden" name="sub_total_gross_amt" value="{$form.sub_total_gross_amt}" />
<input type="hidden" name="sub_total_amt" value="{$form.sub_total_amt}" />
<input type="hidden" name="total_gross_amt" value="{$form.total_gross_amt}" />
<input type="hidden" name="sheet_gst_discount" value="{$form.sheet_gst_discount}" />
<input type="hidden" name="total_gst_amt" value="{$form.total_gst_amt}" />
<input type="hidden" name="sub_total_foreign_gross_amt" value="{$form.sub_total_foreign_gross_amt}" />
<input type="hidden" name="sub_total_foreign_amt" value="{$form.sub_total_foreign_amt}" />
<input type="hidden" name="total_foreign_gross_amt" value="{$form.total_foreign_gross_amt}" />
<input type="hidden" name="total_foreign_gst_amt" value="{$form.total_foreign_gst_amt}" />
<input type="hidden" name="sheet_foreign_gst_discount" value="{$form.sheet_foreign_gst_discount}" />
<input type="hidden" name="gross_foreign_discount_amount" value="{$form.gross_foreign_discount_amount}" />

<table border="0" cellspacing="0" cellpadding="4">
	<tr>
		<th width="120" align="left">Date</th>
		<td><input name="date" id="added1" size="12" onchange="on_date_changed();" value="{$form.date|default:$smarty.now|date_format:"%Y-%m-%d"}" />
			{if !$readonly}
				<img align=absmiddle src="ui/calendar.gif" id="t_added1" style="cursor: pointer;" title="Select Date" />
			{/if}
		</td>
	</tr>
	{if $form.id<$time_value}
		<tr>
			<td align="left"><b>Owner</b></td>
			<td style="color:blue;">{$form.username}</td>
		</tr>
	{/if}
	<tr>
	    <td align="left"><b>Discount</b></td>
	    <td>
			<input type="text" name="discount" size="10" style="text-align:right" value="{$form.discount}" onChange="discount_changed();" />%
		</td>
	</tr>
	{if $config.consignment_modules && $config.masterfile_branch_region && $config.consignment_multiple_currency}
		<tr>
			<td><b>Exchange Rate</b></td>
			<td>
				<input type="text" name="exchange_rate" size="15" value="{if $form.exchange_rate ne 1}{$form.exchange_rate}{/if}" onchange="this.value=float(this.value); foreign_variable_handler(true);" class="r" 
				{if !$form.exchange_rate or $form.exchange_rate eq 1}disabled{/if}
				/>
			</td>
		</tr>
	{/if}
	<tr>
		<td valign="top"><b>Remarks</b></td>
		<td>
			<textarea rows="2" cols="68" name="remark" onchange="uc(this);">{$form.remark}</textarea>
		</td>
	</tr>
	<tr>
	    <th align="left">From</th>
	    <td>
			{if $form.branch_id}
			    {$branches[$form.branch_id].code} - {$branches[$form.branch_id].description}
			{else}
				{$branches[$sessioninfo.branch_id].code} - {$branches[$sessioninfo.branch_id].description}
   			{/if}
		</td>
	</tr>
	<tr>
	    <th align="left">To</th>
	    <td>
	        <select name="to_branch_id" onChange="active_btn(this);" {if $form.mr_branch_id && $form.mr_year && $form.mr_month}onfocus="this.blur(); alert('Cannot change this option because this document is generated by Monthly Report.');" readonly{/if}>
	            <option value="">-- Please Select --</option>
		        {foreach from=$branches key=bid item=b}
				    {if !$branch_group.have_group.$bid}
				    	<option value="{$bid}" {if $bid eq $form.to_branch_id}selected {/if}>{$b.code} - {$b.description}</option>
				    {/if}
				{/foreach}
				{foreach from=$branch_group.header key=bgid item=bg}
				    <optgroup label="{$bg.code}">
				        {foreach from=$branch_group.items.$bgid key=bid item=b}
				            <option value="{$bid}" {if $form.to_branch_id eq $bid}selected {/if}>{$b.code} - {$b.description}</option>
				        {/foreach}
				    </optgroup>
				{/foreach}
		    </select>
		    <span id="span_invoice_to_change_loading"></span>
	    </td>
	</tr>
	<tr>
	    <th align="left" valign="top">Settings</th>
	    <td style="background-color: #F3F3F0; border: 1px solid #CCCCCC;padding: 5px;">
	        <input type="checkbox" name="auto_split_by_price_type" align="absmiddle" {if $form.auto_split_by_price_type}checked  {/if} value="1" /> Auto Split by Price Type when confirm.<br />
			{if $form.is_under_gst && $gst_export_settings}
				{*<input type="checkbox" name="is_export" align="absmiddle" {if $form.is_export}checked{/if} onclick="on_export_clicked(this);" value="1" /> Export to foreign customer. (all GST code selections will be disabled and default as {$gst_export_settings.code} [{$gst_export_settings.rate}%])<br />*}
			{/if}
	    </td>
	</tr>
</table>

<div id="srefresh" style="display:none; padding-top:10px; padding-left:130px; ">
<input id="refresh_btn" type="button" onclick="void(refresh_tables())" style="font-size:1.5em; color:#fff; background:#091" value="click here to continue">
</div>
</div>

<br />
<div id="div_sheets" style="{if !$form.to_branch_id}display:none;{/if}">{include file='consignment.credit_note.open.sheet.tpl'}

{if !$readonly}
	<div style="background:#ddd;border:1px solid #999;">
		{include file='sku_items_autocomplete.tpl' multiple_add=1}
		<span id="autocomplete_sku_indicator" style="padding:2px;background:yellow;display:none;"><img src="ui/clock.gif" align="absmiddle" /> Loading...</span>
	</div>
	<script>reset_sku_autocomplete();</script>
{/if}
</div>

</form>

<p id="p_submit_btn" align="center">
    {if $form.is_approval and $form.status==1 and $form.approved==0 and $form.approval_screen}
		<input type="button" value="Approve" style="background-color:#f90; color:#fff;" onclick="do_approve()">
		<input type="button" value="Reject" style="background-color:#f90; color:#fff;" onclick="do_reject()">
		<input type="button" value="Terminate" style="background-color:#900; color:#fff;" onclick="do_cancel()">
	{/if}

	{if !$form.approval_screen}
		{if !$readonly}
			{if (!$form.status || $form.status==2) and $form.branch_id}
			<input name="bsubmit" type="button" value="Save & Close" style="font:bold 20px Arial; background-color:#f90; color:#fff;" onclick="do_save()" />
			{/if}

			{if $form.id<$time_value}
				<input type="button" value="Delete" style="font:bold 20px Arial; background-color:#900; color:#fff;" onclick="do_delete()" />
			{else}
				<input type="button" value="Close" style="font:bold 20px Arial; background-color:#09c; color:#fff;" onclick="document.location='{$smarty.server.PHP_SELF}'" />
			{/if}

			{if (!$form.status || $form.status==2) and $form.branch_id}
			<input type="button" value="Confirm" style="font:bold 20px Arial; background-color:#091; color:#fff;" onclick="do_confirm()" />
			{/if}
		{else}
		    {if $form.approved and ($sessioninfo.level>=$config.doc_reset_level)}
		        <input type="button" value="Reset" style="font:bold 20px Arial; background-color:#900; color:#fff;" onclick="do_reset();" />
		    {/if}
			<input type="button" value="Close" style="font:bold 20px Arial; background-color:#09c; color:#fff;" onclick="document.location='{$smarty.server.PHP_SELF}'" />
		{/if}
	{/if}
</p>

{include file='footer.tpl'}


<script>
CN_MODULE.initilize();

{if $config.consignment_modules && $config.masterfile_branch_region && $config.consignment_multiple_currency}
	foreign_variable_handler(true);
	//change_lost_inv_branch();
{/if}

{if $readonly}
	Form.disable(document.f_a);
{else}
	{literal}
	new Ajax.PeriodicalUpdater('', "dummy.php", {frequency:1500});
	new Draggable('div_process_gst_price',{ handle: 'div_process_gst_price_header'});
	{/literal}
	init_calendar();
 	//recalc_total();
	calc_all_items();
{/if}


</script>
