{*
2017-04-21 10:41 AM Qiu Ying
- Bug fixed on error message shown in file when download empty file
*}

<div style="display:none;">
	<form id="filter-form" class="form" onsubmit="return false;">
		<input type="hidden" id="schedule_type" name="schedule_type" value="{$smarty.request.schedule_type|default:'active'}"/>
	</form>
</div>
<div class="card mx-3">
	<div class="card-body">
		<div class="table-responsive">
			<table width="100%" cellpadding="4"style="padding:2px" class="report_table table mb-0 text-md-nowrap  table-hover">
				<thead class="bg-gray-100">
					<tr>
						<th></th>
						<th>Branch</th>
						<th>Batch No.</th>
						<th>Date From</th>
						<th>Date To</th>
						<th>Format</th>
						<th>Status</th>
						<th>File Size</th>
						<th>Generated On</th>
						<th>Generated By</th>
					</tr>
				</thead>
				{if $list}
					{foreach from=$list item=l}
						{assign var=tmp value="`$l.id`-`$l.branch_id`"}
						<tbody class="fs-08">
							<tr id="data-row-{$l.id}-{$l.branch_id}" {if $smarty.request.selected_row eq $tmp}class="selected highlight_row"{/if} bgcolor="{cycle values=",#eeeeee"}" >
								<td class="data-action">
									{if $l.status eq "Error"}
										<img src="/ui/messages.gif" alt="Error" title="Error"/>
									{/if}
									{if $l.started}
										{if $l.completed}
											<a href="javascript:void(0);" onclick="CUSTOM_ACC_EXPORT.do_download({$l.id}, {$l.branch_id});"><img src="/ui/application_put.png" alt="Download" title="Download"/></a>
											{if $sessioninfo.id eq $l.user_id || $sessioninfo.level gte 9999}
												{if !$l.archived}
													<a href="javascript:void(0);" onclick="CUSTOM_ACC_EXPORT.reset({$l.id}, {$l.branch_id});"><img src="/ui/refresh.png" alt="Regenerate" title="Regenerate"/></a>
													<a href="javascript:void(0);" onclick="CUSTOM_ACC_EXPORT.archive({$l.id}, {$l.branch_id});"><img src="/ui/icons/compress.png" alt="Archive" title="Archive"/></a>
												{elseif $l.archived}
													<a href="javascript:void(0);" onclick="CUSTOM_ACC_EXPORT.reactivate({$l.id}, {$l.branch_id});"><img src="/ui/icons/arrow_undo.png" alt="Change Back to Active" title="Change Back to Active"/></a>
												{/if}
											{/if}
										{else}
											<img src=/ui/clock.gif align=absmiddle>
										{/if}
									{else}
										{if $sessioninfo.id eq $l.user_id || $sessioninfo.level gte 9999}
										<a href="javascript:void(0);" onclick="CUSTOM_ACC_EXPORT.start_now({$l.id}, 0, {$l.branch_id});"><img src="/ui/icons/control_play_blue.png" alt="Start" title="Start"/></a>
										{/if}
									{/if}
									{if !$l.archived && ($sessioninfo.id eq $l.user_id || $sessioninfo.level gte 9999)}
										<a href="javascript:void(0);" onclick="CUSTOM_ACC_EXPORT.remove_schedule({$l.id}, {$l.branch_id});"><img src="/ui/icons/cancel.png" alt="Remove" title="Remove"/></a>
									{/if}
									{if $smarty.request.debug}
										<a href="{$smarty.server.PHP_SELF}?a=show_debug&id={$l.id}&branch_id={$l.branch_id}" target="_blank">Debug</a>
									{/if}
								</td>
								<td>{$l.branch_code}</td>
								<td>{$l.batchno}</td>
								<td style="text-align:center;">{$l.date_from}</td>
								<td style="text-align:center;">{$l.date_to}</td>
								<td>{$l.title}</td>
								<td style="text-align:center;">{$l.status}</td>
								<td class="data-file_size" style="text-align: right;">{$l.file_size|formatBytes}</td>
								<td style="text-align:center;">{$l.generate_on}</td>
								<td style="text-align:center;">{$l.u}</td>
							</tr>
						</tbody>
					{/foreach}
				{else}
					<tr>
						<td colspan="12"><center>&nbsp;&nbsp;&nbsp;No Record Found</center></td>
					</tr>
				{/if}
			</table>
		</div>
	</div>
</div>
